(** Receipt outcome classification. Matches the TLA+ spec
    [ReceiptOutcomeSet = {"receipt_unset", "receipt_skipped",
    "receipt_done", "receipt_failed", "receipt_cancelled"}] modulo the
    [receipt_unset] variant which is the initial-state-only marker and
    so cannot appear on a terminal receipt. The four terminal variants
    here cover every reachable outcome of a finished turn. See
    [specs/keeper-turn-fsm/KeeperTurnFSM.tla] invariants
    [EveryTurnHasTerminalReceipt] and [ReceiptMatchesState], and
    [specs/keeper-state-machine/KeeperOutcomesConservation.tla].
    [`Skipped] is generated by the [PhaseGateSkip] action: the turn
    reached terminal [Done] without dispatching to a provider, so it is
    a successful no-op rather than a failure or cancellation. *)
type outcome_kind =
  [ `Ok
  | `Skipped
  | `Error
  | `Cancelled
  ]

(** Stable serialisation: [`Ok -> "ok"], [`Skipped -> "skipped"],
    [`Error -> "error"], [`Cancelled -> "cancelled"]. Used at the JSON
    boundary while the receipt record still stores the legacy string
    form. *)
val outcome_kind_to_string : outcome_kind -> string

(** TLA+ receipt symbol mapping: [`Ok] serializes as ["ok"] in JSON but
    corresponds to ["receipt_done"] in [KeeperTurnFSM.tla]; [`Error]
    similarly maps to ["receipt_failed"]. *)
val outcome_kind_to_tla_receipt : outcome_kind -> string

(** Parse the legacy string form. Recognises the four terminal kinds
    and returns [None] for everything else (including ["unset"]) so
    callers can decide whether to fail-closed or surface as [`Error]. *)
val outcome_kind_of_string : string -> outcome_kind option

(** [true] for [`Ok] and [`Skipped] (PhaseGateSkip is a successful
    no-op, not a failure). [false] for [`Error] and [`Cancelled].
    Used by dashboard "healthy" classification and action_radius
    success accounting. *)
val outcome_kind_is_terminal_success : outcome_kind -> bool

type error_kind = private Error_kind of string

val error_kind_of_string : string -> error_kind
val error_kind_to_string : error_kind -> string

(** Witness of a [ReceiptIsAuthoritative] invariant violation.
    [outcome] holds the receipt-side string (e.g. ["receipt_done"]);
    [turn_state] is the offending turn-state symbol the caller
    presented. *)
type receipt_authority_violation =
  { outcome : string
  ; turn_state : string
  }

(** Runtime check for the TLA+ [ReceiptIsAuthoritative] invariant
    (specs/keeper-turn-fsm/KeeperTurnFSM.tla:336):
    [receipt_outcome = "receipt_done" => turn_state = "done"].

    Per [ReceiptMatchesState] the [Done] state also accepts
    [receipt_skipped] (PhaseGateSkip path), so this helper enforces
    the receipt-authoritative direction for both [`Ok] and [`Skipped]:
    a successful-terminal receipt MUST be paired with [turn_state =
    "done"]. [`Error] and [`Cancelled] are accepted here without
    further check; pairing them with the right turn_state is the
    responsibility of [ReceiptMatchesState] (a separate invariant).

    [turn_state] is the canonical TLA+ symbol form (e.g. [done],
    [failed], [cancelled], ...). Callers that hold a
    [Keeper_turn_fsm.turn_state] should pass
    [Keeper_turn_fsm.to_tla_symbol s].

    Returns [Error _] (never raises) so the caller can choose to
    fail-closed via [Result.Error] propagation or surface a metric.
    Memory: feedback_keeper_runtime_fail_closed_for_unknown_permissive_default. *)
val assert_receipt_authoritative
  :  outcome:outcome_kind
  -> turn_state:string
  -> (unit, receipt_authority_violation) result

type tool_requirement = Keeper_agent_tool_surface.tool_requirement

type tool_surface =
  { turn_lane : Keeper_agent_tool_surface.turn_lane
  ; tool_surface_class : Keeper_agent_tool_surface.tool_surface_class
  ; tool_requirement : tool_requirement
  ; visible_tool_count : int
  ; tool_gate_enabled : bool
  ; tool_surface_fallback_used : bool
  ; required_tools : string list
  ; required_tool_candidates : string list
  ; missing_required_tools : string list
  ; materialized_tools : string list
  }

(** Phase identifier emitted when a cascade rotation releases the in-flight
    turn slot. Closed set; wire form is [slot_release_phase_to_string]. *)
type slot_release_phase =
  | Retry_setup_failed
  | Retry_scheduled
  | Retry_budget_exhausted
  | Productive_phase_exhausted

val slot_release_phase_to_string : slot_release_phase -> string

(** Generated by [@@deriving tla] on [slot_release_phase]. Lists the wire
    form of every variant, used by the RFC-0065 correspondence harness. *)
val all_symbols : string list

(** Terminal classification of a cascade rotation attempt. Closed set;
    wire form is [cascade_rotation_outcome_to_string]. *)
type cascade_rotation_outcome =
  | Rotation_setup_failed
  | Rotation_retry_scheduled
  | Rotation_budget_exhausted
  | Rotation_slot_phase_exhausted

val cascade_rotation_outcome_to_string : cascade_rotation_outcome -> string

(** Receipt-level summary of how the in-turn cascade attempt sequence
    ended. Closed set; wire form is [cascade_outcome_to_string]. *)
type cascade_outcome =
  | Cascade_passed_to_next_model
  | Cascade_completed
  | Cascade_not_observed
  | Cascade_not_dispatched

val cascade_outcome_to_string : cascade_outcome -> string

(** Receipt-level tool-contract evaluation result. Closed union of three
    producer paths: (i) initial-state sentinel [Contract_unknown];
    (ii) boundary-state overrides [Contract_not_dispatched],
    [Contract_violated], [Contract_no_tool_capable_provider]; (iii) the
    seven classifier outcomes mirrored from
    [Keeper_contract_classifier.contract_status]. *)
type tool_contract_result =
  | Contract_unknown
  | Contract_not_dispatched
  | Contract_violated
  | Contract_tool_surface_mismatch
  | Contract_no_tool_capable_provider
  | Contract_missing_required_tool_use
  | Contract_claim_only_after_owned_task
  | Contract_needs_execution_progress
  | Contract_passive_only
  | Contract_satisfied_completion
  | Contract_satisfied_execution

val tool_contract_result_to_string : tool_contract_result -> string

val tool_contract_result_of_contract_status
  :  Keeper_contract_classifier.contract_status
  -> tool_contract_result

(** {2 Structured contract-violation encoding} *)

(** Encode a tool list into the wire bracket format.
    [[] for empty, [t1,t2] for non-empty. *)
val encode_tool_list : string list -> string

(** Build an extended terminal_reason_code with called and satisfying
    tool lists. Produces:
    [completion_contract_violation:<contract_id>:called[...]:satisfying[...]]
    The prefix [completion_contract_violation:] is preserved so existing
    prefix-matching consumers remain backward-compatible. *)
val encode_contract_violation_reason
  :  called_tools:string list
  -> satisfying_tools:string list
  -> string
  -> string

(** Decode a terminal_reason_code back into its components.
    Returns [Some (contract_id, called_tools, satisfying_tools)] for
    both legacy and extended formats, [None] for non-violation codes.
    Legacy format yields empty tool lists. *)
val decode_contract_violation_reason
  :  string
  -> (string * string list * string list) option

type cascade_rotation_attempt =
  { from_cascade : Cascade_name.t
  ; to_cascade : Cascade_name.t
  ; reason : Keeper_error_classify.degraded_retry_reason
  ; outcome : cascade_rotation_outcome
  ; slot_release_at_phase : slot_release_phase option
  ; productive_phase_elapsed_ms : int option
  ; retry_phase_elapsed_ms : int option
  ; error_kind : error_kind option
  ; error_message : string option
  ; recorded_at : string
  }

type t =
  { keeper_name : string
  ; agent_name : string
  ; trace_id : string
  ; generation : int
  ; turn_count : int option
  ; oas_turn_count : int option
  ; oas_dispatch_mode : string option
  ; oas_internal_cascade_disabled : bool
  ; current_task_id : string option
  ; goal_ids : string list
  ; outcome : outcome_kind
  ; terminal_reason_code : string
  ; response_text_present : bool
  ; model_used : string option
  ; requested_tools : string list
  ; reported_tools : string list
  ; observed_tools : string list
  ; canonical_tools : string list
  ; unexpected_tools : string list
  ; tools_used : string list
  ; tool_contract_result : tool_contract_result
  ; tool_surface : tool_surface
  ; sandbox_kind : Keeper_types.sandbox_profile
  ; sandbox_root : string option
  ; network_mode : Keeper_types.network_mode
  ; approval_profile : string option
  ; approval_profile_derived : bool
  ; cascade_name : Cascade_name.t
  ; cascade_selected_model : string option
  ; cascade_attempt_count : int
  ; cascade_fallback_applied : bool
  ; cascade_outcome : cascade_outcome
  ; oas_internal_cascade_allowed : bool
  ; degraded_retry_applied : bool
  ; degraded_retry_cascade : Cascade_name.t option
  ; fallback_reason : Keeper_error_classify.degraded_retry_reason option
  ; cascade_rotation_attempts : cascade_rotation_attempt list
  ; stop_reason : Cascade_runner.stop_reason option
  ; error_kind : error_kind option
  ; error_message : string option
  ; started_at : string
  ; ended_at : string
  ; extra_system_context_digest : string option
  ; extra_system_context_injected_size : int option
  ; extra_system_context_computed_size : int option
  ; pre_dispatch_compacted : bool
  ; pre_dispatch_compaction_trigger : string option
  ; pre_dispatch_compaction_before_tokens : int option
  ; pre_dispatch_compaction_after_tokens : int option
  }

val stop_reason_to_string : Cascade_runner.stop_reason -> string
val sandbox_kind_of_meta : Keeper_types.keeper_meta -> Keeper_types.sandbox_profile
val to_json : t -> Yojson.Safe.t

(** Enrich a receipt's terminal_reason_code from legacy to extended format.
    Uses [canonical_tools + observed_tools + tools_used] as called and
    [tool_surface.required_tools] as satisfying. Returns the original
    code unchanged if it is not a contract-violation code or already
    contains tool data. *)
val enrich_contract_violation_reason : t -> string

(** Operator-facing classification of a finished turn. Closed set.

    Producer is [operator_disposition]; consumers
    ([needs_operator_broadcast], dashboard JSON, broadcast payload)
    pattern-match exhaustively. The wire form is byte-compatible with the
    pre-typing string ([operator_disposition_kind_to_string]). *)
type operator_disposition_kind =
  | Disp_pass
  | Disp_pause_human
  | Disp_alert_exhausted
  | Disp_fail_open_next_cascade
  | Disp_pass_next_model
  | Disp_user_cancelled
  | Disp_skipped
  | Disp_unknown

val operator_disposition_kind_to_string : operator_disposition_kind -> string

(** Reason paired with [operator_disposition_kind]. Closed set; the wire
    form is byte-compatible with the pre-typing string. *)
type operator_disposition_reason =
  | Reason_healthy
  | Reason_cascade_exhausted
  | Reason_preflight_config_error
  | Reason_degraded_retry
  | Reason_cascade_fallback
  | Reason_provider_runtime_error
  | Reason_internal_error
  | Reason_tool_required_unsatisfied
  | Reason_tool_route_recoverable_failure
  | Reason_turn_livelock_blocked
  | Reason_cancelled
  | Reason_phase_skipped
  | Reason_unmapped_cascade_state

val operator_disposition_reason_to_string : operator_disposition_reason -> string

(** Derived display pair (disposition, reason) computed from receipt fields.
    Exposed for test access; the runtime path consumes it via [append]. *)
val operator_disposition : t -> operator_disposition_kind * operator_disposition_reason

(** [needs_operator_broadcast disposition] returns true when the disposition
    indicates a silent dead-end that operators must be notified about. *)
val needs_operator_broadcast : operator_disposition_kind -> bool

(** Structured payload emitted for [keeper.operator_broadcast_required].
    Exposed so tests can pin the diagnostic fields operators need when a
    keeper turn pauses or stalls silently. *)
val operator_broadcast_payload
  :  t
  -> disposition:operator_disposition_kind
  -> reason:operator_disposition_reason
  -> Yojson.Safe.t

(** Structured watchdog payload. Keeps the exact [stale_seconds] while
    exposing low-cardinality failure/cohort fields for dashboards and issue
    aggregation. *)
val stale_broadcast_payload
  :  keeper_name:string
  -> agent_name:string
  -> cascade_name:Cascade_name.t
  -> trace_id:string
  -> generation:int
  -> failure_reason:Keeper_registry.failure_reason option
  -> stale_seconds:float
  -> last_turn_ts:float
  -> Yojson.Safe.t

val append : Coord.config -> t -> unit
val latest_json : Coord.config -> string -> Yojson.Safe.t option
val latest_json_by_keeper : Coord.config -> string list -> (string * Yojson.Safe.t) list

(** Emit a watchdog-sourced operator_broadcast_required event for a keeper
    that has been Running but not produced a turn within the stale
    threshold. Used by the supervisor watchdog fiber (Step 3 of the
    keeper-pause-broadcast-watchdog change) to convert silent stalls into
    addressable events. *)
val emit_stale_keeper_broadcast
  :  Coord.config
  -> keeper_name:string
  -> agent_name:string
  -> cascade_name:Cascade_name.t
  -> trace_id:string
  -> generation:int
  -> failure_reason:Keeper_registry.failure_reason option
  -> stale_seconds:float
  -> last_turn_ts:float
  -> unit
