(** Agent_reputation — Reputation scoring from existing JSONL data

    Computes agent reputation from task transitions, mention inbox,
    and board posts/comments.
    No new storage — reads from existing `.masc/` JSONL files.

    @since Phase 3B — Keeper Deliberation Engine
*)

type agent_reputation = {
  agent_name: string;
  tasks_completed: int; [@default 0]
  tasks_claimed: int; [@default 0]
  completion_rate: float; [@default 0.0]
  mentions_received: int; [@default 0]
  mentions_responded: int; [@default 0]
  response_rate: float; [@default 0.0]
  board_posts: int; [@default 0]
  board_comments: int; [@default 0]
  overall_score: float; [@default 0.0]
} [@@deriving yojson { strict = false }]

(** {1 Defaults} *)

let default_reputation ~(agent_name : string) : agent_reputation =
  { agent_name;
    tasks_completed = 0;
    tasks_claimed = 0;
    completion_rate = 0.0;
    mentions_received = 0;
    mentions_responded = 0;
    response_rate = 0.0;
    board_posts = 0;
    board_comments = 0;
    overall_score = 0.0;
  }

(** {1 JSON Serialization}

    [agent_reputation_to_yojson] and [agent_reputation_of_yojson] are
    generated by [ppx_deriving_yojson].  The wrappers below preserve
    the legacy [option]-returning API for callers that haven't migrated
    to [result] yet. *)

let reputation_to_json : agent_reputation -> Yojson.Safe.t =
  agent_reputation_to_yojson

let reputation_of_json (json : Yojson.Safe.t) : agent_reputation option =
  match agent_reputation_of_yojson json with
  | Ok r when r.agent_name <> "" -> Some r
  | Ok _ -> None
  | Error msg ->
    Log.Reputation.warn "agent reputation of_json: %s" msg;
    None

(** {1 JSONL Helpers} *)

(** Load a JSONL file, filter out malformed lines. *)
let load_jsonl_safe (path : string) : Yojson.Safe.t list =
  if not (Sys.file_exists path) then []
  else
    match Safe_ops.read_file_safe path with
    | Error _ -> []
    | Ok content ->
      String.split_on_char '\n' content
      |> List.filter (fun line -> String.length (String.trim line) > 0)
      |> List.filter_map (fun line ->
          try Some (Yojson.Safe.from_string line)
          with Yojson.Json_error _ -> None)

(** {1 Task Counting from Coord State} *)

(** Count tasks claimed and completed by an agent from the room's task list.
    Reads task JSON files from `.masc/tasks/`. *)
let count_tasks_from_room (config : Coord.config) ~(agent_name : string)
    : int * int =
  let tasks_dir = Filename.concat (Coord.masc_dir config) "tasks" in
  if not (Sys.file_exists tasks_dir) || not (Sys.is_directory tasks_dir) then
    (0, 0)
  else
    let files =
      try Sys.readdir tasks_dir |> Array.to_list
      with Sys_error _ -> []
    in
    let claimed = ref 0 in
    let completed = ref 0 in
    List.iter (fun fname ->
        if Filename.check_suffix fname ".json" then begin
          let path = Filename.concat tasks_dir fname in
          match Safe_ops.read_json_file_safe path with
          | Error e -> Log.Reputation.debug "task file read failed %s: %s" fname e
          | Ok json ->
            let status = Safe_ops.json_string ~default:"" "status" json in
            let assignee = Safe_ops.json_string ~default:"" "assignee" json in
            if assignee = agent_name then begin
              if status = "claimed" || status = "in_progress" || status = "done" then
                incr claimed;
              if status = "done" then
                incr completed
            end
        end)
      files;
    (!claimed, !completed)

(** {1 Board Counting} *)

(** Count board posts and comments authored by an agent from JSONL files. *)
let count_board_activity (config : Coord.config) ~(agent_name : string)
    : int * int =
  let board_dir = Coord.masc_dir config in
  (* Board posts JSONL *)
  let posts_path = Filename.concat board_dir "board_posts.jsonl" in
  let posts_rows = load_jsonl_safe posts_path in
  let post_count =
    posts_rows
    |> List.filter (fun json ->
        let author = Safe_ops.json_string ~default:"" "author" json in
        author = agent_name)
    |> List.length
  in
  (* Board comments JSONL *)
  let comments_path = Filename.concat board_dir "board_comments.jsonl" in
  let comments_rows = load_jsonl_safe comments_path in
  let comment_count =
    comments_rows
    |> List.filter (fun json ->
        let author = Safe_ops.json_string ~default:"" "author" json in
        author = agent_name)
    |> List.length
  in
  (post_count, comment_count)

(** {1 Mention Counting} *)

let count_mention_activity (config : Coord.config) ~(agent_name : string)
    : int * int =
  let all = Mention_inbox.read_mentions config ~target_agent:agent_name ~limit:10000 in
  let received = List.length all in
  let responded = List.length (List.filter (fun r -> r.Mention_inbox.read_at > 0.0) all) in
  (received, responded)

(** {1 Overall Score Computation} *)

(** {1 Reputation Score Weights}

    Weighted linear combination for overall reputation.
    Rationale: task completion is the primary signal (0.4) because
    it directly measures value delivered. Response rate (0.3) and
    board activity (0.3) are secondary engagement signals.

    Board activity is capped at [board_activity_cap] to prevent
    high-volume low-quality posting from inflating scores.

    TODO(RFC-0001 Phase 3): Register in Runtime_params for tuning. *)
let weight_completion = 0.4
let weight_response   = 0.3
let weight_board      = 0.3
let board_activity_cap = 20.0

let compute_overall_score ~completion_rate ~response_rate
    ~board_posts ~board_comments : float =
  let board_total = float_of_int (board_posts + board_comments) in
  let board_norm = Float.min 1.0 (board_total /. board_activity_cap) in
  (weight_completion *. completion_rate)
  +. (weight_response *. response_rate)
  +. (weight_board *. board_norm)

(** {1 Main Computation} *)

let compute_reputation (config : Coord.config) ~(agent_name : string)
    : agent_reputation =
  let (tasks_claimed, tasks_completed) =
    count_tasks_from_room config ~agent_name
  in
  let completion_rate =
    if tasks_claimed > 0 then
      float_of_int tasks_completed /. float_of_int tasks_claimed
    else 0.0
  in
  let (mentions_received, mentions_responded) =
    count_mention_activity config ~agent_name
  in
  let response_rate =
    if mentions_received > 0 then
      float_of_int mentions_responded /. float_of_int mentions_received
    else 0.0
  in
  let (board_posts, board_comments) = count_board_activity config ~agent_name in
  let overall_score =
    compute_overall_score ~completion_rate ~response_rate ~board_posts ~board_comments
  in
  { agent_name;
    tasks_completed; tasks_claimed; completion_rate;
    mentions_received; mentions_responded; response_rate;
    board_posts; board_comments;
    overall_score;
  }
