// @generated DO NOT EDIT — run `pnpm tokens:build` (source: dashboard/design-system/tokens/source.ts)

export const TOKENS = {
  "bg0": { name: "--bg-0", value: "#0c0b08", tier: "raw", kind: "color" },
  "bg1": { name: "--bg-1", value: "#141210", tier: "raw", kind: "color" },
  "bg2": { name: "--bg-2", value: "#1a1815", tier: "raw", kind: "color" },
  "bg3": { name: "--bg-3", value: "#211e1a", tier: "raw", kind: "color" },
  "bg4": { name: "--bg-4", value: "#2a2621", tier: "raw", kind: "color" },
  "line1": { name: "--line-1", value: "#2a2520", tier: "raw", kind: "color" },
  "line2": { name: "--line-2", value: "#3a332c", tier: "raw", kind: "color" },
  "line3": { name: "--line-3", value: "#4a4137", tier: "raw", kind: "color" },
  "fg1": { name: "--fg-1", value: "#f0e9dc", tier: "raw", kind: "color" },
  "fg2": { name: "--fg-2", value: "#b8ad9a", tier: "raw", kind: "color" },
  "fg3": { name: "--fg-3", value: "#7a7065", tier: "raw", kind: "color" },
  "fg4": { name: "--fg-4", value: "#4a453e", tier: "raw", kind: "color" },
  "brass1": { name: "--brass-1", value: "#d4a14a", tier: "raw", kind: "color" },
  "brass2": { name: "--brass-2", value: "#b8843a", tier: "raw", kind: "color" },
  "brass3": { name: "--brass-3", value: "#8a5f28", tier: "raw", kind: "color" },
  "brassGlow": { name: "--brass-glow", value: "212 161 74", tier: "raw", kind: "color" },
  "ok": { name: "--ok", value: "#6b9e6b", tier: "raw", kind: "color" },
  "warn": { name: "--warn", value: "#c9a24a", tier: "raw", kind: "color" },
  "err": { name: "--err", value: "#c46a5a", tier: "raw", kind: "color" },
  "info": { name: "--info", value: "#6a8eb0", tier: "raw", kind: "color" },
  "idle": { name: "--idle", value: "#6a6a6a", tier: "raw", kind: "color" },
  "stalled": { name: "--stalled", value: "#8a6aa0", tier: "raw", kind: "color" },
  "okGlow": { name: "--ok-glow", value: "107 158 107", tier: "raw", kind: "color" },
  "warnGlow": { name: "--warn-glow", value: "201 162 74", tier: "raw", kind: "color" },
  "errGlow": { name: "--err-glow", value: "196 106 90", tier: "raw", kind: "color" },
  "infoGlow": { name: "--info-glow", value: "106 142 176", tier: "raw", kind: "color" },
  "stalledGlow": { name: "--stalled-glow", value: "138 106 160", tier: "raw", kind: "color" },
  "k1": { name: "--k-1", value: "#c68196", tier: "raw", kind: "color" },
  "k2": { name: "--k-2", value: "#ca8377", tier: "raw", kind: "color" },
  "k3": { name: "--k-3", value: "#c18b5e", tier: "raw", kind: "color" },
  "k4": { name: "--k-4", value: "#ae9654", tier: "raw", kind: "color" },
  "k5": { name: "--k-5", value: "#91a160", tier: "raw", kind: "color" },
  "k6": { name: "--k-6", value: "#6fa87b", tier: "raw", kind: "color" },
  "k7": { name: "--k-7", value: "#51ab9a", tier: "raw", kind: "color" },
  "k8": { name: "--k-8", value: "#4aa7b7", tier: "raw", kind: "color" },
  "k9": { name: "--k-9", value: "#62a0ca", tier: "raw", kind: "color" },
  "k10": { name: "--k-10", value: "#8296d0", tier: "raw", kind: "color" },
  "k11": { name: "--k-11", value: "#a18cc8", tier: "raw", kind: "color" },
  "k12": { name: "--k-12", value: "#b884b3", tier: "raw", kind: "color" },
  "k1Glow": { name: "--k-1-glow", value: "198 129 150", tier: "raw", kind: "color" },
  "k2Glow": { name: "--k-2-glow", value: "202 131 119", tier: "raw", kind: "color" },
  "k3Glow": { name: "--k-3-glow", value: "193 139 94", tier: "raw", kind: "color" },
  "k4Glow": { name: "--k-4-glow", value: "174 150 84", tier: "raw", kind: "color" },
  "k5Glow": { name: "--k-5-glow", value: "145 161 96", tier: "raw", kind: "color" },
  "k6Glow": { name: "--k-6-glow", value: "111 168 123", tier: "raw", kind: "color" },
  "k7Glow": { name: "--k-7-glow", value: "81 171 154", tier: "raw", kind: "color" },
  "k8Glow": { name: "--k-8-glow", value: "74 167 183", tier: "raw", kind: "color" },
  "k9Glow": { name: "--k-9-glow", value: "98 160 202", tier: "raw", kind: "color" },
  "k10Glow": { name: "--k-10-glow", value: "130 150 208", tier: "raw", kind: "color" },
  "k11Glow": { name: "--k-11-glow", value: "161 140 200", tier: "raw", kind: "color" },
  "k12Glow": { name: "--k-12-glow", value: "184 132 179", tier: "raw", kind: "color" },
  "fontSans": { name: "--font-sans", value: "ui-sans-serif, -apple-system, \"SF Pro Text\", \"Inter\", system-ui, sans-serif", tier: "raw", kind: "typography" },
  "fontMono": { name: "--font-mono", value: "ui-monospace, \"SF Mono\", \"JetBrains Mono\", Menlo, monospace", tier: "raw", kind: "typography" },
  "fs9": { name: "--fs-9", value: "9px", tier: "raw", kind: "dimension" },
  "fs10": { name: "--fs-10", value: "10px", tier: "raw", kind: "dimension" },
  "fs11": { name: "--fs-11", value: "11px", tier: "raw", kind: "dimension" },
  "fs12": { name: "--fs-12", value: "12px", tier: "raw", kind: "dimension" },
  "fs13": { name: "--fs-13", value: "13px", tier: "raw", kind: "dimension" },
  "fs14": { name: "--fs-14", value: "14px", tier: "raw", kind: "dimension" },
  "fs16": { name: "--fs-16", value: "16px", tier: "raw", kind: "dimension" },
  "fs20": { name: "--fs-20", value: "20px", tier: "raw", kind: "dimension" },
  "fs28": { name: "--fs-28", value: "28px", tier: "raw", kind: "dimension" },
  "fs36": { name: "--fs-36", value: "36px", tier: "raw", kind: "dimension" },
  "fs56": { name: "--fs-56", value: "56px", tier: "raw", kind: "dimension" },
  "lhTight": { name: "--lh-tight", value: "1.2", tier: "raw", kind: "number" },
  "lhBody": { name: "--lh-body", value: "1.45", tier: "raw", kind: "number" },
  "lhLoose": { name: "--lh-loose", value: "1.6", tier: "raw", kind: "number" },
  "fwReg": { name: "--fw-reg", value: "400", tier: "raw", kind: "number" },
  "fwMed": { name: "--fw-med", value: "500", tier: "raw", kind: "number" },
  "fwSemi": { name: "--fw-semi", value: "600", tier: "raw", kind: "number" },
  "fwBold": { name: "--fw-bold", value: "700", tier: "raw", kind: "number" },
  "trackTight": { name: "--track-tight", value: "-0.01em", tier: "raw", kind: "dimension" },
  "trackNormal": { name: "--track-normal", value: "0", tier: "raw", kind: "dimension" },
  "trackWide": { name: "--track-wide", value: "0.04em", tier: "raw", kind: "dimension" },
  "trackCaps": { name: "--track-caps", value: "0.08em", tier: "raw", kind: "dimension" },
  "sp1": { name: "--sp-1", value: "4px", tier: "raw", kind: "dimension" },
  "sp2": { name: "--sp-2", value: "8px", tier: "raw", kind: "dimension" },
  "sp3": { name: "--sp-3", value: "12px", tier: "raw", kind: "dimension" },
  "sp4": { name: "--sp-4", value: "16px", tier: "raw", kind: "dimension" },
  "sp5": { name: "--sp-5", value: "20px", tier: "raw", kind: "dimension" },
  "sp6": { name: "--sp-6", value: "24px", tier: "raw", kind: "dimension" },
  "sp7": { name: "--sp-7", value: "32px", tier: "raw", kind: "dimension" },
  "sp8": { name: "--sp-8", value: "40px", tier: "raw", kind: "dimension" },
  "sp0h": { name: "--sp-0h", value: "2px", tier: "raw", kind: "dimension" },
  "sp1h": { name: "--sp-1h", value: "6px", tier: "raw", kind: "dimension" },
  "r0": { name: "--r-0", value: "2px", tier: "raw", kind: "dimension" },
  "r1": { name: "--r-1", value: "3px", tier: "raw", kind: "dimension" },
  "r2": { name: "--r-2", value: "5px", tier: "raw", kind: "dimension" },
  "r3": { name: "--r-3", value: "8px", tier: "raw", kind: "dimension" },
  "tFast": { name: "--t-fast", value: "120ms", tier: "raw", kind: "duration" },
  "tMed": { name: "--t-med", value: "200ms", tier: "raw", kind: "duration" },
  "tSlow": { name: "--t-slow", value: "360ms", tier: "raw", kind: "duration" },
  "tXslow": { name: "--t-xslow", value: "600ms", tier: "raw", kind: "duration" },
  "ease": { name: "--ease", value: "cubic-bezier(.2, .7, .2, 1)", tier: "raw", kind: "easing" },
  "easeOut": { name: "--ease-out", value: "cubic-bezier(.16, 1, .3, 1)", tier: "raw", kind: "easing" },
  "easeIn": { name: "--ease-in", value: "cubic-bezier(.7, 0, .84, 0)", tier: "raw", kind: "easing" },
  "easeInout": { name: "--ease-inout", value: "cubic-bezier(.65, 0, .35, 1)", tier: "raw", kind: "easing" },
  "easeSpring": { name: "--ease-spring", value: "cubic-bezier(.34, 1.56, .64, 1)", tier: "raw", kind: "easing" },
  "space1": { name: "--space-1", value: "4px", tier: "raw", kind: "dimension" },
  "space2": { name: "--space-2", value: "8px", tier: "raw", kind: "dimension" },
  "space3": { name: "--space-3", value: "12px", tier: "raw", kind: "dimension" },
  "space4": { name: "--space-4", value: "16px", tier: "raw", kind: "dimension" },
  "space5": { name: "--space-5", value: "24px", tier: "raw", kind: "dimension" },
  "space6": { name: "--space-6", value: "32px", tier: "raw", kind: "dimension" },
  "space7": { name: "--space-7", value: "48px", tier: "raw", kind: "dimension" },
  "space8": { name: "--space-8", value: "64px", tier: "raw", kind: "dimension" },
  "radiusXs": { name: "--radius-xs", value: "2px", tier: "raw", kind: "dimension" },
  "radiusSm": { name: "--radius-sm", value: "4px", tier: "raw", kind: "dimension" },
  "radiusMd": { name: "--radius-md", value: "6px", tier: "raw", kind: "dimension" },
  "radiusLg": { name: "--radius-lg", value: "12px", tier: "raw", kind: "dimension" },
  "radiusPill": { name: "--radius-pill", value: "999px", tier: "raw", kind: "dimension" },
  "radiusCircle": { name: "--radius-circle", value: "50%", tier: "raw", kind: "dimension" },
  "fontDisplay": { name: "--font-display", value: "'Cinzel', 'Noto Sans KR', 'EB Garamond', serif", tier: "raw", kind: "typography" },
  "fontBody": { name: "--font-body", value: "'EB Garamond', 'Noto Sans KR', Georgia, serif", tier: "raw", kind: "typography" },
  "fontUi": { name: "--font-ui", value: "'Noto Sans KR', 'IBM Plex Sans KR', -apple-system, sans-serif", tier: "raw", kind: "typography" },
  "scrollbarThumb": { name: "--scrollbar-thumb", value: "#2a1f1a", tier: "raw", kind: "color" },
  "scrollbarThumbHover": { name: "--scrollbar-thumb-hover", value: "#3d2e22", tier: "raw", kind: "color" },
  "density": { name: "--density", value: "1", tier: "raw", kind: "number" },
  "gridUnit": { name: "--grid-unit", value: "8px", tier: "raw", kind: "dimension" },
  "gridHalf": { name: "--grid-half", value: "4px", tier: "raw", kind: "dimension" },
  "gridDbl": { name: "--grid-dbl", value: "16px", tier: "raw", kind: "dimension" },
  "hTopbar": { name: "--h-topbar", value: "36px", tier: "raw", kind: "dimension" },
  "hTicker": { name: "--h-ticker", value: "32px", tier: "raw", kind: "dimension" },
  "hKpi": { name: "--h-kpi", value: "56px", tier: "raw", kind: "dimension" },
  "hLifeline": { name: "--h-lifeline", value: "28px", tier: "raw", kind: "dimension" },
  "hComposer": { name: "--h-composer", value: "48px", tier: "raw", kind: "dimension" },
  "hDeck": { name: "--h-deck", value: "240px", tier: "raw", kind: "dimension" },
  "wSidebar": { name: "--w-sidebar", value: "168px", tier: "raw", kind: "dimension" },
  "wRail": { name: "--w-rail", value: "300px", tier: "raw", kind: "dimension" },
  "zBase": { name: "--z-base", value: "1", tier: "raw", kind: "number" },
  "zSticky": { name: "--z-sticky", value: "20", tier: "raw", kind: "number" },
  "zDropdown": { name: "--z-dropdown", value: "30", tier: "raw", kind: "number" },
  "zOverlay": { name: "--z-overlay", value: "40", tier: "raw", kind: "number" },
  "zDrawer": { name: "--z-drawer", value: "60", tier: "raw", kind: "number" },
  "zModal": { name: "--z-modal", value: "80", tier: "raw", kind: "number" },
  "zToast": { name: "--z-toast", value: "100", tier: "raw", kind: "number" },
  "fontSize3xs": { name: "--font-size-3xs", value: "10px", tier: "raw", kind: "dimension" },
  "fontSize2xs": { name: "--font-size-2xs", value: "11px", tier: "raw", kind: "dimension" },
  "fontSizeXs": { name: "--font-size-xs", value: "12px", tier: "raw", kind: "dimension" },
  "fontSizeSm": { name: "--font-size-sm", value: "13px", tier: "raw", kind: "dimension" },
  "fontSizeBase": { name: "--font-size-base", value: "14px", tier: "raw", kind: "dimension" },
  "fontSizeMd": { name: "--font-size-md", value: "15px", tier: "raw", kind: "dimension" },
  "fontSizeLg": { name: "--font-size-lg", value: "16px", tier: "raw", kind: "dimension" },
  "spacingElement": { name: "--spacing-element", value: "8px", tier: "raw", kind: "dimension" },
  "spacingGroup": { name: "--spacing-group", value: "12px", tier: "raw", kind: "dimension" },
  "spacingCard": { name: "--spacing-card", value: "16px", tier: "raw", kind: "dimension" },
  "radiusXl": { name: "--radius-xl", value: "24px", tier: "raw", kind: "dimension" },
  "slate400": { name: "--slate-400", value: "#94a3b8", tier: "raw", kind: "color" },
  "slate500": { name: "--slate-500", value: "#64748b", tier: "raw", kind: "color" },
  "slate600": { name: "--slate-600", value: "#475569", tier: "raw", kind: "color" },
  "slate800": { name: "--slate-800", value: "#1e293b", tier: "raw", kind: "color" },
  "blue400": { name: "--blue-400", value: "#60a5fa", tier: "raw", kind: "color" },
  "sky400": { name: "--sky-400", value: "#38bdf8", tier: "raw", kind: "color" },
  "purple500": { name: "--purple-500", value: "#a855f7", tier: "raw", kind: "color" },
  "yellow100": { name: "--yellow-100", value: "#fde68a", tier: "raw", kind: "color" },
  "red100": { name: "--red-100", value: "#fecaca", tier: "raw", kind: "color" },
  "cyan100": { name: "--cyan-100", value: "#cffafe", tier: "raw", kind: "color" },
  "emerald": { name: "--emerald", value: "#22c55e", tier: "raw", kind: "color" },
  "emeraldFg": { name: "--emerald-fg", value: "#bbf7d0", tier: "raw", kind: "color" },
  "indigo": { name: "--indigo", value: "#818cf8", tier: "raw", kind: "color" },
  "yellowBright": { name: "--yellow-bright", value: "#facc15", tier: "raw", kind: "color" },
  "amberBright": { name: "--amber-bright", value: "#f59e0b", tier: "raw", kind: "color" },
  "rose": { name: "--rose", value: "#f43f5e", tier: "raw", kind: "color" },
  "roseFg": { name: "--rose-fg", value: "#fecdd3", tier: "raw", kind: "color" },
  "roseLight": { name: "--rose-light", value: "#fb7185", tier: "raw", kind: "color" },
  "cyan": { name: "--cyan", value: "#22d3ee", tier: "raw", kind: "color" },
  "purple": { name: "--purple", value: "#a78bfa", tier: "raw", kind: "color" },
  "frost100": { name: "--frost-100", value: "#e2e8f0", tier: "raw", kind: "color" },
  "whitePure": { name: "--white-pure", value: "#ffffff", tier: "raw", kind: "color" },
  "textNearWhite": { name: "--text-near-white", value: "#f8fafc", tier: "raw", kind: "color" },
  "textSlateLight": { name: "--text-slate-light", value: "#cbd5e1", tier: "raw", kind: "color" },
  "textStrong": { name: "--text-strong", value: "#eaf1ff", tier: "raw", kind: "color" },
  "textBody": { name: "--text-body", value: "#c0d2f2", tier: "raw", kind: "color" },
  "textMuted": { name: "--text-muted", value: "#a8bfdf", tier: "raw", kind: "color" },
  "textDim": { name: "--text-dim", value: "#a0a8b4", tier: "raw", kind: "color" },
  "stateIdle": { name: "--state-idle", value: "#b8c0cc", tier: "raw", kind: "color" },
  "stateOffline": { name: "--state-offline", value: "#7a8494", tier: "raw", kind: "color" },
  "agentWorking": { name: "--agent-working", value: "#7ae09a", tier: "raw", kind: "color" },
  "agentBusy": { name: "--agent-busy", value: "#f0c060", tier: "raw", kind: "color" },
  "chatUserAvatar": { name: "--chat-user-avatar", value: "#d8f0ff", tier: "raw", kind: "color" },
  "chatUserChip": { name: "--chat-user-chip", value: "#c9ebff", tier: "raw", kind: "color" },
  "chatAssistantAvatar": { name: "--chat-assistant-avatar", value: "#efe6ff", tier: "raw", kind: "color" },
  "chatAssistantChip": { name: "--chat-assistant-chip", value: "#ded0ff", tier: "raw", kind: "color" },
  "chatErrorAvatar": { name: "--chat-error-avatar", value: "#ffe1e1", tier: "raw", kind: "color" },
  "chatErrorChip": { name: "--chat-error-chip", value: "#ffb4b4", tier: "raw", kind: "color" },
  "chatCodeCallout": { name: "--chat-code-callout", value: "#95f3bc", tier: "raw", kind: "color" },
  "voteUp": { name: "--vote-up", value: "#ff4500", tier: "raw", kind: "color" },
  "voteDown": { name: "--vote-down", value: "#7193ff", tier: "raw", kind: "color" },
  "voteHover": { name: "--vote-hover", value: "#ccc", tier: "raw", kind: "color" },
  "textSlate": { name: "--text-slate", value: "#b0bfd4", tier: "raw", kind: "color" },
  "warnBright": { name: "--warn-bright", value: "#f97316", tier: "raw", kind: "color" },
  "badLight": { name: "--bad-light", value: "#f87171", tier: "raw", kind: "color" },
  "okSoft": { name: "--ok-soft", value: "rgb(107 158 107 / .10)", tier: "semantic", kind: "color" },
  "okFg": { name: "--ok-fg", value: "#8ebc8e", tier: "semantic", kind: "color" },
  "okBorder": { name: "--ok-border", value: "rgb(107 158 107 / .35)", tier: "semantic", kind: "color" },
  "okRing": { name: "--ok-ring", value: "0 0 0 1px rgb(107 158 107 / .45), 0 0 8px rgb(107 158 107 / .35)", tier: "semantic", kind: "shadow" },
  "warnSoft": { name: "--warn-soft", value: "rgb(201 162 74 / .12)", tier: "semantic", kind: "color" },
  "warnFg": { name: "--warn-fg", value: "#d9b764", tier: "semantic", kind: "color" },
  "warnBorder": { name: "--warn-border", value: "rgb(201 162 74 / .35)", tier: "semantic", kind: "color" },
  "warnRing": { name: "--warn-ring", value: "0 0 0 1px rgb(201 162 74 / .45), 0 0 8px rgb(201 162 74 / .35)", tier: "semantic", kind: "shadow" },
  "errSoft": { name: "--err-soft", value: "rgb(196 106 90 / .12)", tier: "semantic", kind: "color" },
  "errFg": { name: "--err-fg", value: "#d8806f", tier: "semantic", kind: "color" },
  "errBorder": { name: "--err-border", value: "rgb(196 106 90 / .40)", tier: "semantic", kind: "color" },
  "errRing": { name: "--err-ring", value: "0 0 0 1px rgb(196 106 90 / .50), 0 0 8px rgb(196 106 90 / .40)", tier: "semantic", kind: "shadow" },
  "infoSoft": { name: "--info-soft", value: "rgb(106 142 176 / .12)", tier: "semantic", kind: "color" },
  "infoFg": { name: "--info-fg", value: "#8aa6c4", tier: "semantic", kind: "color" },
  "infoBorder": { name: "--info-border", value: "rgb(106 142 176 / .35)", tier: "semantic", kind: "color" },
  "infoRing": { name: "--info-ring", value: "0 0 0 1px rgb(106 142 176 / .45), 0 0 8px rgb(106 142 176 / .35)", tier: "semantic", kind: "shadow" },
  "idleSoft": { name: "--idle-soft", value: "rgb(106 106 106 / .10)", tier: "semantic", kind: "color" },
  "idleFg": { name: "--idle-fg", value: "#8a8a8a", tier: "semantic", kind: "color" },
  "idleBorder": { name: "--idle-border", value: "rgb(106 106 106 / .30)", tier: "semantic", kind: "color" },
  "stalledSoft": { name: "--stalled-soft", value: "rgb(138 106 160 / .12)", tier: "semantic", kind: "color" },
  "stalledFg": { name: "--stalled-fg", value: "#a88ac0", tier: "semantic", kind: "color" },
  "stalledBorder": { name: "--stalled-border", value: "rgb(138 106 160 / .35)", tier: "semantic", kind: "color" },
  "stalledRing": { name: "--stalled-ring", value: "0 0 0 1px rgb(138 106 160 / .45), 0 0 8px rgb(138 106 160 / .35)", tier: "semantic", kind: "shadow" },
  "brassSoft": { name: "--brass-soft", value: "rgb(212 161 74 / .10)", tier: "semantic", kind: "color" },
  "brassFg": { name: "--brass-fg", value: "var(--brass-1)", tier: "semantic", kind: "color" },
  "brassBorder": { name: "--brass-border", value: "rgb(212 161 74 / .35)", tier: "semantic", kind: "color" },
  "brassRing": { name: "--brass-ring", value: "0 0 0 1px rgb(212 161 74 / .50), 0 0 10px rgb(212 161 74 / .50)", tier: "semantic", kind: "shadow" },
  "k1Soft": { name: "--k-1-soft", value: "rgb(198 129 150 / .10)", tier: "semantic", kind: "color" },
  "k1Border": { name: "--k-1-border", value: "rgb(198 129 150 / .35)", tier: "semantic", kind: "color" },
  "k1Ring": { name: "--k-1-ring", value: "0 0 0 1px rgb(198 129 150 / .45), 0 0 8px rgb(198 129 150 / .35)", tier: "semantic", kind: "shadow" },
  "k2Soft": { name: "--k-2-soft", value: "rgb(202 131 119 / .10)", tier: "semantic", kind: "color" },
  "k2Border": { name: "--k-2-border", value: "rgb(202 131 119 / .35)", tier: "semantic", kind: "color" },
  "k2Ring": { name: "--k-2-ring", value: "0 0 0 1px rgb(202 131 119 / .45), 0 0 8px rgb(202 131 119 / .35)", tier: "semantic", kind: "shadow" },
  "k3Soft": { name: "--k-3-soft", value: "rgb(193 139 94 / .10)", tier: "semantic", kind: "color" },
  "k3Border": { name: "--k-3-border", value: "rgb(193 139 94 / .35)", tier: "semantic", kind: "color" },
  "k3Ring": { name: "--k-3-ring", value: "0 0 0 1px rgb(193 139 94 / .45), 0 0 8px rgb(193 139 94 / .35)", tier: "semantic", kind: "shadow" },
  "k4Soft": { name: "--k-4-soft", value: "rgb(174 150 84 / .10)", tier: "semantic", kind: "color" },
  "k4Border": { name: "--k-4-border", value: "rgb(174 150 84 / .35)", tier: "semantic", kind: "color" },
  "k4Ring": { name: "--k-4-ring", value: "0 0 0 1px rgb(174 150 84 / .45), 0 0 8px rgb(174 150 84 / .35)", tier: "semantic", kind: "shadow" },
  "k5Soft": { name: "--k-5-soft", value: "rgb(145 161 96 / .10)", tier: "semantic", kind: "color" },
  "k5Border": { name: "--k-5-border", value: "rgb(145 161 96 / .35)", tier: "semantic", kind: "color" },
  "k5Ring": { name: "--k-5-ring", value: "0 0 0 1px rgb(145 161 96 / .45), 0 0 8px rgb(145 161 96 / .35)", tier: "semantic", kind: "shadow" },
  "k6Soft": { name: "--k-6-soft", value: "rgb(111 168 123 / .10)", tier: "semantic", kind: "color" },
  "k6Border": { name: "--k-6-border", value: "rgb(111 168 123 / .35)", tier: "semantic", kind: "color" },
  "k6Ring": { name: "--k-6-ring", value: "0 0 0 1px rgb(111 168 123 / .45), 0 0 8px rgb(111 168 123 / .35)", tier: "semantic", kind: "shadow" },
  "k7Soft": { name: "--k-7-soft", value: "rgb(81 171 154 / .10)", tier: "semantic", kind: "color" },
  "k7Border": { name: "--k-7-border", value: "rgb(81 171 154 / .35)", tier: "semantic", kind: "color" },
  "k7Ring": { name: "--k-7-ring", value: "0 0 0 1px rgb(81 171 154 / .45), 0 0 8px rgb(81 171 154 / .35)", tier: "semantic", kind: "shadow" },
  "k8Soft": { name: "--k-8-soft", value: "rgb(74 167 183 / .10)", tier: "semantic", kind: "color" },
  "k8Border": { name: "--k-8-border", value: "rgb(74 167 183 / .35)", tier: "semantic", kind: "color" },
  "k8Ring": { name: "--k-8-ring", value: "0 0 0 1px rgb(74 167 183 / .45), 0 0 8px rgb(74 167 183 / .35)", tier: "semantic", kind: "shadow" },
  "k9Soft": { name: "--k-9-soft", value: "rgb(98 160 202 / .10)", tier: "semantic", kind: "color" },
  "k9Border": { name: "--k-9-border", value: "rgb(98 160 202 / .35)", tier: "semantic", kind: "color" },
  "k9Ring": { name: "--k-9-ring", value: "0 0 0 1px rgb(98 160 202 / .45), 0 0 8px rgb(98 160 202 / .35)", tier: "semantic", kind: "shadow" },
  "k10Soft": { name: "--k-10-soft", value: "rgb(130 150 208 / .10)", tier: "semantic", kind: "color" },
  "k10Border": { name: "--k-10-border", value: "rgb(130 150 208 / .35)", tier: "semantic", kind: "color" },
  "k10Ring": { name: "--k-10-ring", value: "0 0 0 1px rgb(130 150 208 / .45), 0 0 8px rgb(130 150 208 / .35)", tier: "semantic", kind: "shadow" },
  "k11Soft": { name: "--k-11-soft", value: "rgb(161 140 200 / .10)", tier: "semantic", kind: "color" },
  "k11Border": { name: "--k-11-border", value: "rgb(161 140 200 / .35)", tier: "semantic", kind: "color" },
  "k11Ring": { name: "--k-11-ring", value: "0 0 0 1px rgb(161 140 200 / .45), 0 0 8px rgb(161 140 200 / .35)", tier: "semantic", kind: "shadow" },
  "k12Soft": { name: "--k-12-soft", value: "rgb(184 132 179 / .10)", tier: "semantic", kind: "color" },
  "k12Border": { name: "--k-12-border", value: "rgb(184 132 179 / .35)", tier: "semantic", kind: "color" },
  "k12Ring": { name: "--k-12-ring", value: "0 0 0 1px rgb(184 132 179 / .45), 0 0 8px rgb(184 132 179 / .35)", tier: "semantic", kind: "shadow" },
  "colorBgPage": { name: "--color-bg-page", value: "var(--bg-0)", tier: "role", kind: "color" },
  "colorBgSurface": { name: "--color-bg-surface", value: "var(--bg-1)", tier: "role", kind: "color" },
  "colorBgPanelAlt": { name: "--color-bg-panel-alt", value: "var(--bg-2)", tier: "role", kind: "color" },
  "colorBgElevated": { name: "--color-bg-elevated", value: "var(--bg-3)", tier: "role", kind: "color" },
  "colorBgHover": { name: "--color-bg-hover", value: "var(--bg-4)", tier: "role", kind: "color" },
  "colorFgPrimary": { name: "--color-fg-primary", value: "var(--fg-1)", tier: "role", kind: "color" },
  "colorFgSecondary": { name: "--color-fg-secondary", value: "var(--fg-2)", tier: "role", kind: "color" },
  "colorFgMuted": { name: "--color-fg-muted", value: "var(--fg-3)", tier: "role", kind: "color" },
  "colorFgDisabled": { name: "--color-fg-disabled", value: "var(--fg-4)", tier: "role", kind: "color" },
  "colorBorderDefault": { name: "--color-border-default", value: "var(--line-1)", tier: "role", kind: "color" },
  "colorBorderStrong": { name: "--color-border-strong", value: "var(--line-2)", tier: "role", kind: "color" },
  "colorBorderDivider": { name: "--color-border-divider", value: "var(--line-3)", tier: "role", kind: "color" },
  "colorAccentFg": { name: "--color-accent-fg", value: "var(--brass-1)", tier: "role", kind: "color" },
  "colorAccentFgDim": { name: "--color-accent-fg-dim", value: "var(--brass-3)", tier: "role", kind: "color" },
  "colorAccentGlow": { name: "--color-accent-glow", value: "var(--brass-glow)", tier: "role", kind: "color" },
  "colorStatusOk": { name: "--color-status-ok", value: "var(--ok)", tier: "role", kind: "color" },
  "colorStatusWarn": { name: "--color-status-warn", value: "var(--warn)", tier: "role", kind: "color" },
  "colorStatusErr": { name: "--color-status-err", value: "var(--err)", tier: "role", kind: "color" },
  "colorStatusInfo": { name: "--color-status-info", value: "var(--info)", tier: "role", kind: "color" },
  "colorStatusIdle": { name: "--color-status-idle", value: "var(--idle)", tier: "role", kind: "color" },
  "colorStatusStalled": { name: "--color-status-stalled", value: "var(--stalled)", tier: "role", kind: "color" },
  "colorKeeper1": { name: "--color-keeper-1", value: "var(--k-1)", tier: "role", kind: "color" },
  "colorKeeper2": { name: "--color-keeper-2", value: "var(--k-2)", tier: "role", kind: "color" },
  "colorKeeper3": { name: "--color-keeper-3", value: "var(--k-3)", tier: "role", kind: "color" },
  "colorKeeper4": { name: "--color-keeper-4", value: "var(--k-4)", tier: "role", kind: "color" },
  "colorKeeper5": { name: "--color-keeper-5", value: "var(--k-5)", tier: "role", kind: "color" },
  "colorKeeper6": { name: "--color-keeper-6", value: "var(--k-6)", tier: "role", kind: "color" },
  "colorKeeper7": { name: "--color-keeper-7", value: "var(--k-7)", tier: "role", kind: "color" },
  "colorKeeper8": { name: "--color-keeper-8", value: "var(--k-8)", tier: "role", kind: "color" },
  "colorKeeper9": { name: "--color-keeper-9", value: "var(--k-9)", tier: "role", kind: "color" },
  "colorKeeper10": { name: "--color-keeper-10", value: "var(--k-10)", tier: "role", kind: "color" },
  "colorKeeper11": { name: "--color-keeper-11", value: "var(--k-11)", tier: "role", kind: "color" },
  "colorKeeper12": { name: "--color-keeper-12", value: "var(--k-12)", tier: "role", kind: "color" },
  "colorFocusRing": { name: "--color-focus-ring", value: "var(--brass-1)", tier: "role", kind: "color" },
  "colorStatusAdded": { name: "--color-status-added", value: "var(--ok)", tier: "role", kind: "color" },
  "colorStatusModified": { name: "--color-status-modified", value: "var(--warn)", tier: "role", kind: "color" },
  "colorStatusDeleted": { name: "--color-status-deleted", value: "var(--err)", tier: "role", kind: "color" },
  "typeMicro": { name: "--type-micro", value: "var(--fs-9)/var(--lh-tight) var(--font-mono)", tier: "role", kind: "typography" },
  "typeCaption": { name: "--type-caption", value: "var(--fs-10)/var(--lh-tight) var(--font-mono)", tier: "role", kind: "typography" },
  "typeLabel": { name: "--type-label", value: "var(--fs-11)/var(--lh-tight) var(--font-sans)", tier: "role", kind: "typography" },
  "typeMeta": { name: "--type-meta", value: "var(--fs-12)/var(--lh-tight) var(--font-mono)", tier: "role", kind: "typography" },
  "typeBody": { name: "--type-body", value: "var(--fs-13)/var(--lh-body) var(--font-sans)", tier: "role", kind: "typography" },
  "typeCode": { name: "--type-code", value: "var(--fs-12)/var(--lh-body) var(--font-mono)", tier: "role", kind: "typography" },
  "typeTitle": { name: "--type-title", value: "var(--fs-14)/var(--lh-tight) var(--font-sans)", tier: "role", kind: "typography" },
  "typeKpiM": { name: "--type-kpi-m", value: "var(--fs-16)/var(--lh-tight) var(--font-mono)", tier: "role", kind: "typography" },
  "typeKpiL": { name: "--type-kpi-l", value: "var(--fs-20)/var(--lh-tight) var(--font-mono)", tier: "role", kind: "typography" },
  "typeHero": { name: "--type-hero", value: "var(--fs-28)/var(--lh-tight) var(--font-mono)", tier: "role", kind: "typography" },
  "typeDisplay": { name: "--type-display", value: "var(--fs-36)/var(--lh-tight) var(--font-mono)", tier: "role", kind: "typography" },
  "spInline": { name: "--sp-inline", value: "calc(var(--density) * 4px)", tier: "role", kind: "dimension" },
  "spGutter": { name: "--sp-gutter", value: "calc(var(--density) * 8px)", tier: "role", kind: "dimension" },
  "spStack": { name: "--sp-stack", value: "calc(var(--density) * 12px)", tier: "role", kind: "dimension" },
  "spSection": { name: "--sp-section", value: "calc(var(--density) * 20px)", tier: "role", kind: "dimension" },
  "spRegion": { name: "--sp-region", value: "calc(var(--density) * 32px)", tier: "role", kind: "dimension" },
  "rowHMicro": { name: "--row-h-micro", value: "calc(var(--density) * 18px)", tier: "role", kind: "dimension" },
  "rowHTight": { name: "--row-h-tight", value: "calc(var(--density) * 22px)", tier: "role", kind: "dimension" },
  "rowH": { name: "--row-h", value: "calc(var(--density) * 26px)", tier: "role", kind: "dimension" },
  "rowHLoose": { name: "--row-h-loose", value: "calc(var(--density) * 32px)", tier: "role", kind: "dimension" },
  "rowHTall": { name: "--row-h-tall", value: "calc(var(--density) * 40px)", tier: "role", kind: "dimension" },
  "ctrlHXs": { name: "--ctrl-h-xs", value: "calc(var(--density) * 16px)", tier: "role", kind: "dimension" },
  "ctrlHSm": { name: "--ctrl-h-sm", value: "calc(var(--density) * 20px)", tier: "role", kind: "dimension" },
  "ctrlH": { name: "--ctrl-h", value: "calc(var(--density) * 24px)", tier: "role", kind: "dimension" },
  "ctrlHLg": { name: "--ctrl-h-lg", value: "calc(var(--density) * 28px)", tier: "role", kind: "dimension" },
  "_densityScope": { name: "--_density-scope", value: "1", tier: "role", kind: "number" },
  "elev0Bg": { name: "--elev-0-bg", value: "var(--bg-0)", tier: "role", kind: "color" },
  "elev0Border": { name: "--elev-0-border", value: "transparent", tier: "role", kind: "color" },
  "elev0Shadow": { name: "--elev-0-shadow", value: "none", tier: "role", kind: "shadow" },
  "elev1Bg": { name: "--elev-1-bg", value: "var(--bg-1)", tier: "role", kind: "color" },
  "elev1Border": { name: "--elev-1-border", value: "var(--line-1)", tier: "role", kind: "color" },
  "elev1Shadow": { name: "--elev-1-shadow", value: "0 1px 0 rgb(0 0 0 / .4)", tier: "role", kind: "shadow" },
  "elev2Bg": { name: "--elev-2-bg", value: "var(--bg-2)", tier: "role", kind: "color" },
  "elev2Border": { name: "--elev-2-border", value: "var(--line-1)", tier: "role", kind: "color" },
  "elev2Shadow": { name: "--elev-2-shadow", value: "0 1px 0 rgb(0 0 0 / .4), inset 0 1px 0 rgb(255 255 255 / .02)", tier: "role", kind: "shadow" },
  "elev3Bg": { name: "--elev-3-bg", value: "var(--bg-3)", tier: "role", kind: "color" },
  "elev3Border": { name: "--elev-3-border", value: "var(--line-2)", tier: "role", kind: "color" },
  "elev3Shadow": { name: "--elev-3-shadow", value: "0 2px 6px rgb(0 0 0 / .45), inset 0 1px 0 rgb(255 255 255 / .03)", tier: "role", kind: "shadow" },
  "elev4Bg": { name: "--elev-4-bg", value: "var(--bg-3)", tier: "role", kind: "color" },
  "elev4Border": { name: "--elev-4-border", value: "var(--line-2)", tier: "role", kind: "color" },
  "elev4Shadow": { name: "--elev-4-shadow", value: "0 6px 18px rgb(0 0 0 / .55), 0 0 0 1px var(--line-2), inset 0 1px 0 rgb(255 255 255 / .03)", tier: "role", kind: "shadow" },
  "elev5Bg": { name: "--elev-5-bg", value: "var(--bg-3)", tier: "role", kind: "color" },
  "elev5Border": { name: "--elev-5-border", value: "var(--line-3)", tier: "role", kind: "color" },
  "elev5Shadow": { name: "--elev-5-shadow", value: "0 12px 32px rgb(0 0 0 / .6), 0 0 0 1px var(--line-3), inset 0 1px 0 rgb(255 255 255 / .04)", tier: "role", kind: "shadow" },
  "elev6Bg": { name: "--elev-6-bg", value: "var(--bg-3)", tier: "role", kind: "color" },
  "elev6Border": { name: "--elev-6-border", value: "var(--line-3)", tier: "role", kind: "color" },
  "elev6Shadow": { name: "--elev-6-shadow", value: "0 24px 64px rgb(0 0 0 / .7), 0 0 0 1px var(--line-3), inset 0 1px 0 rgb(255 255 255 / .04)", tier: "role", kind: "shadow" },
  "shadow1": { name: "--shadow-1", value: "var(--elev-2-shadow)", tier: "role", kind: "shadow" },
  "shadow2": { name: "--shadow-2", value: "var(--elev-4-shadow)", tier: "role", kind: "shadow" },
  "shadow3": { name: "--shadow-3", value: "var(--elev-5-shadow)", tier: "role", kind: "shadow" },
  "shadowInset": { name: "--shadow-inset", value: "inset 0 1px 0 rgb(255 255 255 / .03)", tier: "role", kind: "shadow" },
  "shadowCard": { name: "--shadow-card", value: "0 1px 4px rgba(0, 0, 0, 0.5)", tier: "role", kind: "shadow" },
  "shadowPanel": { name: "--shadow-panel", value: "0 2px 12px rgba(0, 0, 0, 0.6)", tier: "role", kind: "shadow" },
  "shadowGlow": { name: "--shadow-glow", value: "0 0 20px var(--accent-glow)", tier: "role", kind: "shadow" },
  "shadowRaised": { name: "--shadow-raised", value: "0 8px 24px rgba(0, 0, 0, 0.55), 0 0 0 1px var(--border-highlight)", tier: "role", kind: "shadow" },
  "shadowRing": { name: "--shadow-ring", value: "inset 0 0 0 1px rgba(196, 162, 101, 0.25)", tier: "role", kind: "shadow" },
  "shadowCmdPalette": { name: "--shadow-cmd-palette", value: "0 12px 40px rgb(0 0 0 / .6)", tier: "role", kind: "shadow" },
  "shadowDrawerLeft": { name: "--shadow-drawer-left", value: "-8px 0 24px rgb(0 0 0 / .4)", tier: "role", kind: "shadow" },
  "focusRing": { name: "--focus-ring", value: "0 0 0 1px var(--brass-1), 0 0 0 3px rgb(var(--brass-glow) / .25)", tier: "role", kind: "shadow" },
  "focusRingErr": { name: "--focus-ring-err", value: "0 0 0 1px var(--err), 0 0 0 3px rgb(var(--err-glow) / .3)", tier: "role", kind: "shadow" },
  "hoverOverlay": { name: "--hover-overlay", value: "rgb(255 255 255 / .03)", tier: "role", kind: "color" },
  "hoverOverlayStrong": { name: "--hover-overlay-strong", value: "rgb(255 255 255 / .05)", tier: "role", kind: "color" },
  "activeOverlay": { name: "--active-overlay", value: "rgb(0 0 0 / .25)", tier: "role", kind: "color" },
  "pressedScale": { name: "--pressed-scale", value: "0.97", tier: "role", kind: "number" },
  "hoverLift": { name: "--hover-lift", value: "-1px", tier: "role", kind: "dimension" },
  "focusRingWidth": { name: "--focus-ring-width", value: "2px", tier: "role", kind: "dimension" },
  "focusRingOffset": { name: "--focus-ring-offset", value: "2px", tier: "role", kind: "dimension" },
  "buttonPrimaryBg": { name: "--button-primary-bg", value: "var(--accent-12)", tier: "role", kind: "color" },
  "buttonPrimaryFg": { name: "--button-primary-fg", value: "var(--color-fg-secondary)", tier: "role", kind: "color" },
  "buttonPrimaryBorder": { name: "--button-primary-border", value: "var(--accent-30)", tier: "role", kind: "color" },
  "buttonPrimaryBgHover": { name: "--button-primary-bg-hover", value: "var(--accent-20)", tier: "role", kind: "color" },
  "buttonPrimaryBgPressed": { name: "--button-primary-bg-pressed", value: "var(--accent-20)", tier: "role", kind: "color" },
  "buttonGhostBg": { name: "--button-ghost-bg", value: "var(--white-4)", tier: "role", kind: "color" },
  "buttonGhostFg": { name: "--button-ghost-fg", value: "var(--color-fg-primary)", tier: "role", kind: "color" },
  "buttonGhostBorder": { name: "--button-ghost-border", value: "var(--color-border-default)", tier: "role", kind: "color" },
  "buttonGhostBgHover": { name: "--button-ghost-bg-hover", value: "var(--white-8)", tier: "role", kind: "color" },
  "buttonGhostBgPressed": { name: "--button-ghost-bg-pressed", value: "var(--accent-12)", tier: "role", kind: "color" },
  "buttonDangerBg": { name: "--button-danger-bg", value: "var(--bad-10)", tier: "role", kind: "color" },
  "buttonDangerFg": { name: "--button-danger-fg", value: "var(--bad-light)", tier: "role", kind: "color" },
  "buttonDangerBorder": { name: "--button-danger-border", value: "var(--bad-30)", tier: "role", kind: "color" },
  "buttonDangerBgHover": { name: "--button-danger-bg-hover", value: "var(--bad-20)", tier: "role", kind: "color" },
  "buttonDangerBgPressed": { name: "--button-danger-bg-pressed", value: "var(--bad-20)", tier: "role", kind: "color" },
  "buttonOkBg": { name: "--button-ok-bg", value: "var(--ok-10)", tier: "role", kind: "color" },
  "buttonOkFg": { name: "--button-ok-fg", value: "var(--color-status-ok)", tier: "role", kind: "color" },
  "buttonOkBorder": { name: "--button-ok-border", value: "var(--ok-20)", tier: "role", kind: "color" },
  "buttonOkBgHover": { name: "--button-ok-bg-hover", value: "var(--ok-20)", tier: "role", kind: "color" },
  "buttonOkBgPressed": { name: "--button-ok-bg-pressed", value: "var(--ok-20)", tier: "role", kind: "color" },
  "buttonWarnBg": { name: "--button-warn-bg", value: "var(--warn-14)", tier: "role", kind: "color" },
  "buttonWarnFg": { name: "--button-warn-fg", value: "var(--color-status-warn)", tier: "role", kind: "color" },
  "buttonWarnBorder": { name: "--button-warn-border", value: "transparent", tier: "role", kind: "color" },
  "buttonWarnBgHover": { name: "--button-warn-bg-hover", value: "var(--warn-24)", tier: "role", kind: "color" },
  "buttonWarnBgPressed": { name: "--button-warn-bg-pressed", value: "var(--warn-24)", tier: "role", kind: "color" },
  "buttonSubtleBg": { name: "--button-subtle-bg", value: "transparent", tier: "role", kind: "color" },
  "buttonSubtleFg": { name: "--button-subtle-fg", value: "var(--color-fg-muted)", tier: "role", kind: "color" },
  "buttonSubtleBorder": { name: "--button-subtle-border", value: "transparent", tier: "role", kind: "color" },
  "buttonSubtleBgHover": { name: "--button-subtle-bg-hover", value: "var(--white-6)", tier: "role", kind: "color" },
  "buttonSubtleBgPressed": { name: "--button-subtle-bg-pressed", value: "var(--white-6)", tier: "role", kind: "color" },
  "inputBg": { name: "--input-bg", value: "var(--white-4)", tier: "role", kind: "color" },
  "inputFg": { name: "--input-fg", value: "var(--color-fg-primary)", tier: "role", kind: "color" },
  "inputBorder": { name: "--input-border", value: "var(--color-border-default)", tier: "role", kind: "color" },
  "inputBgHover": { name: "--input-bg-hover", value: "var(--white-6)", tier: "role", kind: "color" },
  "inputBgFocus": { name: "--input-bg-focus", value: "var(--color-bg-page)", tier: "role", kind: "color" },
  "inputPlaceholder": { name: "--input-placeholder", value: "var(--color-fg-muted)", tier: "role", kind: "color" },
  "inputBorderFocus": { name: "--input-border-focus", value: "rgba(71,184,255,0.6)", tier: "role", kind: "color" },
  "dialogPanelBg": { name: "--dialog-panel-bg", value: "rgba(13,21,38,0.98)", tier: "role", kind: "color" },
  "dialogPanelBorder": { name: "--dialog-panel-border", value: "var(--color-border-default)", tier: "role", kind: "color" },
  "dialogOverlayBg": { name: "--dialog-overlay-bg", value: "var(--white-5)", tier: "role", kind: "color" },
  "toastBg": { name: "--toast-bg", value: "rgba(10,18,34,0.96)", tier: "role", kind: "color" },
  "stateHoverBg": { name: "--state-hover-bg", value: "var(--bg-3)", tier: "role", kind: "color" },
  "stateHoverFg": { name: "--state-hover-fg", value: "var(--fg-1)", tier: "role", kind: "color" },
  "stateHoverBorder": { name: "--state-hover-border", value: "var(--line-2)", tier: "role", kind: "color" },
  "stateSelectedBg": { name: "--state-selected-bg", value: "var(--bg-4)", tier: "role", kind: "color" },
  "stateSelectedFg": { name: "--state-selected-fg", value: "var(--fg-1)", tier: "role", kind: "color" },
  "stateSelectedBorder": { name: "--state-selected-border", value: "var(--line-3)", tier: "role", kind: "color" },
  "statePressedBg": { name: "--state-pressed-bg", value: "rgb(0 0 0 / .4)", tier: "role", kind: "color" },
  "stateActiveBg": { name: "--state-active-bg", value: "rgb(var(--brass-glow) / .08)", tier: "role", kind: "color" },
  "stateActiveFg": { name: "--state-active-fg", value: "var(--brass-1)", tier: "role", kind: "color" },
  "stateActiveBorder": { name: "--state-active-border", value: "var(--brass-3)", tier: "role", kind: "color" },
  "stateDisabledFg": { name: "--state-disabled-fg", value: "var(--fg-4)", tier: "role", kind: "color" },
  "stateDisabledBg": { name: "--state-disabled-bg", value: "transparent", tier: "role", kind: "color" },
  "divider": { name: "--divider", value: "var(--line-1)", tier: "role", kind: "color" },
  "dividerEmphasis": { name: "--divider-emphasis", value: "var(--line-2)", tier: "role", kind: "color" },
  "dividerZone": { name: "--divider-zone", value: "var(--line-3)", tier: "role", kind: "color" },
  "scrimSubtle": { name: "--scrim-subtle", value: "rgb(0 0 0 / .3)", tier: "role", kind: "color" },
  "scrim": { name: "--scrim", value: "rgb(0 0 0 / .5)", tier: "role", kind: "color" },
  "scrimStrong": { name: "--scrim-strong", value: "rgb(0 0 0 / .7)", tier: "role", kind: "color" },
  "scrimBrass": { name: "--scrim-brass", value: "rgb(var(--brass-glow) / .04)", tier: "role", kind: "color" },
  "bgTabStickyHover": { name: "--bg-tab-sticky-hover", value: "rgb(30 41 59 / .95)", tier: "role", kind: "color" },
  "tabBg": { name: "--tab-bg", value: "var(--bg-1)", tier: "role", kind: "color" },
  "tabBgActive": { name: "--tab-bg-active", value: "var(--bg-2)", tier: "role", kind: "color" },
  "tabBgHover": { name: "--tab-bg-hover", value: "var(--bg-2)", tier: "role", kind: "color" },
  "tabFg": { name: "--tab-fg", value: "var(--fg-3)", tier: "role", kind: "color" },
  "tabFgActive": { name: "--tab-fg-active", value: "var(--fg-1)", tier: "role", kind: "color" },
  "tabBorder": { name: "--tab-border", value: "var(--line-1)", tier: "role", kind: "color" },
  "tabIndicator": { name: "--tab-indicator", value: "var(--brass-1)", tier: "role", kind: "color" },
  "tabCloseHover": { name: "--tab-close-hover", value: "var(--err)", tier: "role", kind: "color" },
  "sidebarBg": { name: "--sidebar-bg", value: "var(--bg-1)", tier: "role", kind: "color" },
  "sidebarFg": { name: "--sidebar-fg", value: "var(--fg-2)", tier: "role", kind: "color" },
  "sidebarItemHoverBg": { name: "--sidebar-item-hover-bg", value: "var(--bg-2)", tier: "role", kind: "color" },
  "sidebarItemActiveBg": { name: "--sidebar-item-active-bg", value: "var(--bg-3)", tier: "role", kind: "color" },
  "sidebarIconFg": { name: "--sidebar-icon-fg", value: "var(--fg-3)", tier: "role", kind: "color" },
  "sidebarIconActiveFg": { name: "--sidebar-icon-active-fg", value: "var(--brass-1)", tier: "role", kind: "color" },
  "sidebarSectionHeaderFg": { name: "--sidebar-section-header-fg", value: "var(--fg-3)", tier: "role", kind: "color" },
  "sidebarBorder": { name: "--sidebar-border", value: "var(--line-1)", tier: "role", kind: "color" },
  "panelHeaderBg": { name: "--panel-header-bg", value: "var(--bg-1)", tier: "role", kind: "color" },
  "panelHeaderFg": { name: "--panel-header-fg", value: "var(--fg-2)", tier: "role", kind: "color" },
  "panelResizeHandle": { name: "--panel-resize-handle", value: "var(--line-1)", tier: "role", kind: "color" },
  "panelResizeHandleHover": { name: "--panel-resize-handle-hover", value: "var(--brass-3)", tier: "role", kind: "color" },
  "terminalBg": { name: "--terminal-bg", value: "var(--bg-0)", tier: "role", kind: "color" },
  "terminalFg": { name: "--terminal-fg", value: "var(--fg-1)", tier: "role", kind: "color" },
  "terminalPrompt": { name: "--terminal-prompt", value: "var(--brass-1)", tier: "role", kind: "color" },
  "terminalCursor": { name: "--terminal-cursor", value: "var(--brass-1)", tier: "role", kind: "color" },
  "terminalSelectionBg": { name: "--terminal-selection-bg", value: "rgb(var(--brass-glow) / .15)", tier: "role", kind: "color" },
  "menuBg": { name: "--menu-bg", value: "var(--bg-3)", tier: "role", kind: "color" },
  "menuBorder": { name: "--menu-border", value: "var(--line-2)", tier: "role", kind: "color" },
  "menuShadow": { name: "--menu-shadow", value: "var(--shadow-2)", tier: "role", kind: "shadow" },
  "menuSeparator": { name: "--menu-separator", value: "var(--line-1)", tier: "role", kind: "color" },
  "menuitemFg": { name: "--menuitem-fg", value: "var(--fg-1)", tier: "role", kind: "color" },
  "menuitemHoverBg": { name: "--menuitem-hover-bg", value: "var(--bg-4)", tier: "role", kind: "color" },
  "menuitemActiveBg": { name: "--menuitem-active-bg", value: "rgb(var(--brass-glow) / .08)", tier: "role", kind: "color" },
  "menuitemDisabledFg": { name: "--menuitem-disabled-fg", value: "var(--fg-4)", tier: "role", kind: "color" },
  "menuShortcutFg": { name: "--menu-shortcut-fg", value: "var(--fg-3)", tier: "role", kind: "color" },
  "tooltipBg": { name: "--tooltip-bg", value: "var(--bg-3)", tier: "role", kind: "color" },
  "tooltipFg": { name: "--tooltip-fg", value: "var(--fg-1)", tier: "role", kind: "color" },
  "tooltipBorder": { name: "--tooltip-border", value: "var(--line-2)", tier: "role", kind: "color" },
  "tooltipShadow": { name: "--tooltip-shadow", value: "var(--shadow-1)", tier: "role", kind: "shadow" },
  "toastBgInfo": { name: "--toast-bg-info", value: "var(--info-soft)", tier: "role", kind: "color" },
  "toastBgSuccess": { name: "--toast-bg-success", value: "var(--ok-soft)", tier: "role", kind: "color" },
  "toastBgWarning": { name: "--toast-bg-warning", value: "var(--warn-soft)", tier: "role", kind: "color" },
  "toastBgError": { name: "--toast-bg-error", value: "var(--err-soft)", tier: "role", kind: "color" },
  "toastFg": { name: "--toast-fg", value: "var(--fg-1)", tier: "role", kind: "color" },
  "toastBorder": { name: "--toast-border", value: "var(--line-2)", tier: "role", kind: "color" },
  "toastShadow": { name: "--toast-shadow", value: "var(--shadow-3)", tier: "role", kind: "shadow" },
  "terminalAnsiBlack": { name: "--terminal-ansi-black", value: "var(--bg-0)", tier: "role", kind: "color" },
  "terminalAnsiRed": { name: "--terminal-ansi-red", value: "var(--err)", tier: "role", kind: "color" },
  "terminalAnsiGreen": { name: "--terminal-ansi-green", value: "var(--ok)", tier: "role", kind: "color" },
  "terminalAnsiYellow": { name: "--terminal-ansi-yellow", value: "var(--warn)", tier: "role", kind: "color" },
  "terminalAnsiBlue": { name: "--terminal-ansi-blue", value: "var(--info)", tier: "role", kind: "color" },
  "terminalAnsiMagenta": { name: "--terminal-ansi-magenta", value: "var(--k-12)", tier: "role", kind: "color" },
  "terminalAnsiCyan": { name: "--terminal-ansi-cyan", value: "var(--k-8)", tier: "role", kind: "color" },
  "terminalAnsiWhite": { name: "--terminal-ansi-white", value: "var(--fg-2)", tier: "role", kind: "color" },
  "terminalAnsiBrightBlack": { name: "--terminal-ansi-bright-black", value: "var(--fg-3)", tier: "role", kind: "color" },
  "terminalAnsiBrightRed": { name: "--terminal-ansi-bright-red", value: "var(--err-fg)", tier: "role", kind: "color" },
  "terminalAnsiBrightGreen": { name: "--terminal-ansi-bright-green", value: "var(--ok-fg)", tier: "role", kind: "color" },
  "terminalAnsiBrightYellow": { name: "--terminal-ansi-bright-yellow", value: "var(--warn-fg)", tier: "role", kind: "color" },
  "terminalAnsiBrightBlue": { name: "--terminal-ansi-bright-blue", value: "var(--info-fg)", tier: "role", kind: "color" },
  "terminalAnsiBrightMagenta": { name: "--terminal-ansi-bright-magenta", value: "var(--k-11)", tier: "role", kind: "color" },
  "terminalAnsiBrightCyan": { name: "--terminal-ansi-bright-cyan", value: "var(--k-9)", tier: "role", kind: "color" },
  "terminalAnsiBrightWhite": { name: "--terminal-ansi-bright-white", value: "var(--fg-1)", tier: "role", kind: "color" },
  "motionEnter": { name: "--motion-enter", value: "var(--t-med) var(--ease-out)", tier: "role", kind: "duration" },
  "motionExit": { name: "--motion-exit", value: "var(--t-fast) var(--ease-in)", tier: "role", kind: "duration" },
  "motionSwap": { name: "--motion-swap", value: "var(--t-fast) var(--ease)", tier: "role", kind: "duration" },
  "motionReveal": { name: "--motion-reveal", value: "var(--t-slow) var(--ease-out)", tier: "role", kind: "duration" },
  "motionSettle": { name: "--motion-settle", value: "var(--t-xslow) var(--ease-out)", tier: "role", kind: "duration" },
  "motionPop": { name: "--motion-pop", value: "var(--t-med) var(--ease-spring)", tier: "role", kind: "duration" },
  "enterDuration": { name: "--enter-duration", value: "var(--t-med)", tier: "role", kind: "duration" },
  "exitDuration": { name: "--exit-duration", value: "var(--t-fast)", tier: "role", kind: "duration" },
  "enterEasing": { name: "--enter-easing", value: "var(--ease-out)", tier: "role", kind: "easing" },
  "exitEasing": { name: "--exit-easing", value: "var(--ease-in)", tier: "role", kind: "easing" },
  "_motionScope": { name: "--_motion-scope", value: "1", tier: "role", kind: "number" },
  "cmtQuestion": { name: "--cmt-question", value: "var(--info)", tier: "role", kind: "color" },
  "cmtFlag": { name: "--cmt-flag", value: "var(--err)", tier: "role", kind: "color" },
  "cmtNote": { name: "--cmt-note", value: "var(--fg-2)", tier: "role", kind: "color" },
  "cmtApprove": { name: "--cmt-approve", value: "var(--ok)", tier: "role", kind: "color" },
  "cmtSuggest": { name: "--cmt-suggest", value: "var(--brass-1)", tier: "role", kind: "color" },
  "diffAdd": { name: "--diff-add", value: "rgb(107 158 107 / .08)", tier: "role", kind: "color" },
  "diffDel": { name: "--diff-del", value: "rgb(196 106 90 / .08)", tier: "role", kind: "color" },
  "diffAddBar": { name: "--diff-add-bar", value: "rgb(107 158 107 / .35)", tier: "role", kind: "color" },
  "diffDelBar": { name: "--diff-del-bar", value: "rgb(196 106 90 / .35)", tier: "role", kind: "color" },
  "heat1": { name: "--heat-1", value: "rgb(212 161 74 / .04)", tier: "role", kind: "color" },
  "heat2": { name: "--heat-2", value: "rgb(212 161 74 / .08)", tier: "role", kind: "color" },
  "heat3": { name: "--heat-3", value: "rgb(212 161 74 / .14)", tier: "role", kind: "color" },
  "colorTextBody": { name: "--color-text-body", value: "var(--fg-2)", tier: "role", kind: "color" },
  "colorTextMuted": { name: "--color-text-muted", value: "var(--fg-3)", tier: "role", kind: "color" },
  "colorTextDim": { name: "--color-text-dim", value: "var(--fg-3)", tier: "role", kind: "color" },
  "colorAccentBrass": { name: "--color-accent-brass", value: "var(--brass-1)", tier: "role", kind: "color" },
  "colorAccentSoft": { name: "--color-accent-soft", value: "var(--brass-soft)", tier: "role", kind: "color" },
  "colorKeeper1Glow": { name: "--color-keeper-1-glow", value: "var(--k-1-glow)", tier: "role", kind: "color" },
  "colorKeeper2Glow": { name: "--color-keeper-2-glow", value: "var(--k-2-glow)", tier: "role", kind: "color" },
  "colorKeeper3Glow": { name: "--color-keeper-3-glow", value: "var(--k-3-glow)", tier: "role", kind: "color" },
  "colorKeeper4Glow": { name: "--color-keeper-4-glow", value: "var(--k-4-glow)", tier: "role", kind: "color" },
  "colorKeeper5Glow": { name: "--color-keeper-5-glow", value: "var(--k-5-glow)", tier: "role", kind: "color" },
  "colorKeeper6Glow": { name: "--color-keeper-6-glow", value: "var(--k-6-glow)", tier: "role", kind: "color" },
  "colorKeeper7Glow": { name: "--color-keeper-7-glow", value: "var(--k-7-glow)", tier: "role", kind: "color" },
  "colorKeeper8Glow": { name: "--color-keeper-8-glow", value: "var(--k-8-glow)", tier: "role", kind: "color" },
  "colorKeeper9Glow": { name: "--color-keeper-9-glow", value: "var(--k-9-glow)", tier: "role", kind: "color" },
  "colorKeeper10Glow": { name: "--color-keeper-10-glow", value: "var(--k-10-glow)", tier: "role", kind: "color" },
  "colorKeeper11Glow": { name: "--color-keeper-11-glow", value: "var(--k-11-glow)", tier: "role", kind: "color" },
  "colorKeeper12Glow": { name: "--color-keeper-12-glow", value: "var(--k-12-glow)", tier: "role", kind: "color" },
} as const;

export type TokenName = keyof typeof TOKENS;
export type TokenVar = typeof TOKENS[TokenName]["name"];

/** `var(--token-name)` for the given token. */
export const tokenVar = (k: TokenName): string => `var(${TOKENS[k].name})`;
