(* @generated DO NOT EDIT — run `pnpm tokens:build` (source: dashboard/design-system/tokens/source.ts) *)

(** MASC Cockpit design tokens — strongly-typed accessors for ppx_css.

    Use [var_of] to obtain a CSS [var(--...)] reference:
    {[
      let style = [%css {|
        background: %{Tokens.var_of `Color_bg_page};
        color:      %{Tokens.var_of `Color_fg_primary};
      |}]
    ]}
*)

type semantic =
  [
  | `Bg_0
  | `Bg_1
  | `Bg_2
  | `Bg_3
  | `Bg_4
  | `Line_1
  | `Line_2
  | `Line_3
  | `Fg_1
  | `Fg_2
  | `Fg_3
  | `Fg_4
  | `Brass_1
  | `Brass_2
  | `Brass_3
  | `Brass_glow
  | `Ok
  | `Warn
  | `Err
  | `Info
  | `Idle
  | `Stalled
  | `Ok_glow
  | `Warn_glow
  | `Err_glow
  | `Info_glow
  | `Stalled_glow
  | `K_1
  | `K_2
  | `K_3
  | `K_4
  | `K_5
  | `K_6
  | `K_7
  | `K_8
  | `K_9
  | `K_10
  | `K_11
  | `K_12
  | `K_1_glow
  | `K_2_glow
  | `K_3_glow
  | `K_4_glow
  | `K_5_glow
  | `K_6_glow
  | `K_7_glow
  | `K_8_glow
  | `K_9_glow
  | `K_10_glow
  | `K_11_glow
  | `K_12_glow
  | `Font_sans
  | `Font_mono
  | `Fs_9
  | `Fs_10
  | `Fs_11
  | `Fs_12
  | `Fs_13
  | `Fs_14
  | `Fs_16
  | `Fs_20
  | `Fs_28
  | `Fs_36
  | `Fs_56
  | `Lh_tight
  | `Lh_body
  | `Lh_loose
  | `Fw_reg
  | `Fw_med
  | `Fw_semi
  | `Fw_bold
  | `Track_tight
  | `Track_normal
  | `Track_wide
  | `Track_caps
  | `Sp_1
  | `Sp_2
  | `Sp_3
  | `Sp_4
  | `Sp_5
  | `Sp_6
  | `Sp_7
  | `Sp_8
  | `Sp_0h
  | `Sp_1h
  | `R_0
  | `R_1
  | `R_2
  | `R_3
  | `T_fast
  | `T_med
  | `T_slow
  | `T_xslow
  | `Ease
  | `Ease_out
  | `Ease_in
  | `Ease_inout
  | `Ease_spring
  | `Space_1
  | `Space_2
  | `Space_3
  | `Space_4
  | `Space_5
  | `Space_6
  | `Space_7
  | `Space_8
  | `Radius_xs
  | `Radius_sm
  | `Radius_md
  | `Radius_lg
  | `Radius_pill
  | `Radius_circle
  | `Font_display
  | `Font_body
  | `Font_ui
  | `Scrollbar_thumb
  | `Scrollbar_thumb_hover
  | `Density
  | `Grid_unit
  | `Grid_half
  | `Grid_dbl
  | `H_topbar
  | `H_ticker
  | `H_kpi
  | `H_lifeline
  | `H_composer
  | `H_deck
  | `W_sidebar
  | `W_rail
  | `Z_base
  | `Z_sticky
  | `Z_dropdown
  | `Z_overlay
  | `Z_drawer
  | `Z_modal
  | `Z_toast
  | `Font_size_3xs
  | `Font_size_2xs
  | `Font_size_xs
  | `Font_size_sm
  | `Font_size_base
  | `Font_size_md
  | `Font_size_lg
  | `Spacing_element
  | `Spacing_group
  | `Spacing_card
  | `Radius_xl
  | `Slate_400
  | `Slate_500
  | `Slate_600
  | `Slate_800
  | `Blue_400
  | `Sky_400
  | `Purple_500
  | `Yellow_100
  | `Red_100
  | `Cyan_100
  | `Emerald
  | `Emerald_fg
  | `Indigo
  | `Yellow_bright
  | `Amber_bright
  | `Rose
  | `Rose_fg
  | `Rose_light
  | `Cyan
  | `Purple
  | `Frost_100
  | `White_pure
  | `Text_near_white
  | `Text_slate_light
  | `Text_strong
  | `Text_body
  | `Text_muted
  | `Text_dim
  | `State_idle
  | `State_offline
  | `Agent_working
  | `Agent_busy
  | `Chat_user_avatar
  | `Chat_user_chip
  | `Chat_assistant_avatar
  | `Chat_assistant_chip
  | `Chat_error_avatar
  | `Chat_error_chip
  | `Chat_code_callout
  | `Vote_up
  | `Vote_down
  | `Vote_hover
  | `Text_slate
  | `Warn_bright
  | `Bad_light
  | `Ok_soft
  | `Ok_fg
  | `Ok_border
  | `Ok_ring
  | `Warn_soft
  | `Warn_fg
  | `Warn_border
  | `Warn_ring
  | `Err_soft
  | `Err_fg
  | `Err_border
  | `Err_ring
  | `Info_soft
  | `Info_fg
  | `Info_border
  | `Info_ring
  | `Idle_soft
  | `Idle_fg
  | `Idle_border
  | `Stalled_soft
  | `Stalled_fg
  | `Stalled_border
  | `Stalled_ring
  | `Brass_soft
  | `Brass_fg
  | `Brass_border
  | `Brass_ring
  | `K_1_soft
  | `K_1_border
  | `K_1_ring
  | `K_2_soft
  | `K_2_border
  | `K_2_ring
  | `K_3_soft
  | `K_3_border
  | `K_3_ring
  | `K_4_soft
  | `K_4_border
  | `K_4_ring
  | `K_5_soft
  | `K_5_border
  | `K_5_ring
  | `K_6_soft
  | `K_6_border
  | `K_6_ring
  | `K_7_soft
  | `K_7_border
  | `K_7_ring
  | `K_8_soft
  | `K_8_border
  | `K_8_ring
  | `K_9_soft
  | `K_9_border
  | `K_9_ring
  | `K_10_soft
  | `K_10_border
  | `K_10_ring
  | `K_11_soft
  | `K_11_border
  | `K_11_ring
  | `K_12_soft
  | `K_12_border
  | `K_12_ring
  | `Color_bg_page
  | `Color_bg_surface
  | `Color_bg_panel_alt
  | `Color_bg_elevated
  | `Color_bg_hover
  | `Color_fg_primary
  | `Color_fg_secondary
  | `Color_fg_muted
  | `Color_fg_disabled
  | `Color_border_default
  | `Color_border_strong
  | `Color_border_divider
  | `Color_accent_fg
  | `Color_accent_fg_dim
  | `Color_accent_glow
  | `Color_status_ok
  | `Color_status_warn
  | `Color_status_err
  | `Color_status_info
  | `Color_status_idle
  | `Color_status_stalled
  | `Color_keeper_1
  | `Color_keeper_2
  | `Color_keeper_3
  | `Color_keeper_4
  | `Color_keeper_5
  | `Color_keeper_6
  | `Color_keeper_7
  | `Color_keeper_8
  | `Color_keeper_9
  | `Color_keeper_10
  | `Color_keeper_11
  | `Color_keeper_12
  | `Color_focus_ring
  | `Color_status_added
  | `Color_status_modified
  | `Color_status_deleted
  | `Type_micro
  | `Type_caption
  | `Type_label
  | `Type_meta
  | `Type_body
  | `Type_code
  | `Type_title
  | `Type_kpi_m
  | `Type_kpi_l
  | `Type_hero
  | `Type_display
  | `Sp_inline
  | `Sp_gutter
  | `Sp_stack
  | `Sp_section
  | `Sp_region
  | `Row_h_micro
  | `Row_h_tight
  | `Row_h
  | `Row_h_loose
  | `Row_h_tall
  | `Ctrl_h_xs
  | `Ctrl_h_sm
  | `Ctrl_h
  | `Ctrl_h_lg
  | `_density_scope
  | `Elev_0_bg
  | `Elev_0_border
  | `Elev_0_shadow
  | `Elev_1_bg
  | `Elev_1_border
  | `Elev_1_shadow
  | `Elev_2_bg
  | `Elev_2_border
  | `Elev_2_shadow
  | `Elev_3_bg
  | `Elev_3_border
  | `Elev_3_shadow
  | `Elev_4_bg
  | `Elev_4_border
  | `Elev_4_shadow
  | `Elev_5_bg
  | `Elev_5_border
  | `Elev_5_shadow
  | `Elev_6_bg
  | `Elev_6_border
  | `Elev_6_shadow
  | `Shadow_1
  | `Shadow_2
  | `Shadow_3
  | `Shadow_inset
  | `Shadow_card
  | `Shadow_panel
  | `Shadow_glow
  | `Shadow_raised
  | `Shadow_ring
  | `Shadow_cmd_palette
  | `Shadow_drawer_left
  | `Focus_ring
  | `Focus_ring_err
  | `Hover_overlay
  | `Hover_overlay_strong
  | `Active_overlay
  | `Pressed_scale
  | `Hover_lift
  | `Focus_ring_width
  | `Focus_ring_offset
  | `Button_primary_bg
  | `Button_primary_fg
  | `Button_primary_border
  | `Button_primary_bg_hover
  | `Button_primary_bg_pressed
  | `Button_ghost_bg
  | `Button_ghost_fg
  | `Button_ghost_border
  | `Button_ghost_bg_hover
  | `Button_ghost_bg_pressed
  | `Button_danger_bg
  | `Button_danger_fg
  | `Button_danger_border
  | `Button_danger_bg_hover
  | `Button_danger_bg_pressed
  | `Button_ok_bg
  | `Button_ok_fg
  | `Button_ok_border
  | `Button_ok_bg_hover
  | `Button_ok_bg_pressed
  | `Button_warn_bg
  | `Button_warn_fg
  | `Button_warn_border
  | `Button_warn_bg_hover
  | `Button_warn_bg_pressed
  | `Button_subtle_bg
  | `Button_subtle_fg
  | `Button_subtle_border
  | `Button_subtle_bg_hover
  | `Button_subtle_bg_pressed
  | `Input_bg
  | `Input_fg
  | `Input_border
  | `Input_bg_hover
  | `Input_bg_focus
  | `Input_placeholder
  | `Input_border_focus
  | `Dialog_panel_bg
  | `Dialog_panel_border
  | `Dialog_overlay_bg
  | `Toast_bg
  | `State_hover_bg
  | `State_hover_fg
  | `State_hover_border
  | `State_selected_bg
  | `State_selected_fg
  | `State_selected_border
  | `State_pressed_bg
  | `State_active_bg
  | `State_active_fg
  | `State_active_border
  | `State_disabled_fg
  | `State_disabled_bg
  | `Divider
  | `Divider_emphasis
  | `Divider_zone
  | `Scrim_subtle
  | `Scrim
  | `Scrim_strong
  | `Scrim_brass
  | `Bg_tab_sticky_hover
  | `Tab_bg
  | `Tab_bg_active
  | `Tab_bg_hover
  | `Tab_fg
  | `Tab_fg_active
  | `Tab_border
  | `Tab_indicator
  | `Tab_close_hover
  | `Sidebar_bg
  | `Sidebar_fg
  | `Sidebar_item_hover_bg
  | `Sidebar_item_active_bg
  | `Sidebar_icon_fg
  | `Sidebar_icon_active_fg
  | `Sidebar_section_header_fg
  | `Sidebar_border
  | `Panel_header_bg
  | `Panel_header_fg
  | `Panel_resize_handle
  | `Panel_resize_handle_hover
  | `Terminal_bg
  | `Terminal_fg
  | `Terminal_prompt
  | `Terminal_cursor
  | `Terminal_selection_bg
  | `Menu_bg
  | `Menu_border
  | `Menu_shadow
  | `Menu_separator
  | `Menuitem_fg
  | `Menuitem_hover_bg
  | `Menuitem_active_bg
  | `Menuitem_disabled_fg
  | `Menu_shortcut_fg
  | `Tooltip_bg
  | `Tooltip_fg
  | `Tooltip_border
  | `Tooltip_shadow
  | `Toast_bg_info
  | `Toast_bg_success
  | `Toast_bg_warning
  | `Toast_bg_error
  | `Toast_fg
  | `Toast_border
  | `Toast_shadow
  | `Terminal_ansi_black
  | `Terminal_ansi_red
  | `Terminal_ansi_green
  | `Terminal_ansi_yellow
  | `Terminal_ansi_blue
  | `Terminal_ansi_magenta
  | `Terminal_ansi_cyan
  | `Terminal_ansi_white
  | `Terminal_ansi_bright_black
  | `Terminal_ansi_bright_red
  | `Terminal_ansi_bright_green
  | `Terminal_ansi_bright_yellow
  | `Terminal_ansi_bright_blue
  | `Terminal_ansi_bright_magenta
  | `Terminal_ansi_bright_cyan
  | `Terminal_ansi_bright_white
  | `Motion_enter
  | `Motion_exit
  | `Motion_swap
  | `Motion_reveal
  | `Motion_settle
  | `Motion_pop
  | `Enter_duration
  | `Exit_duration
  | `Enter_easing
  | `Exit_easing
  | `_motion_scope
  | `Cmt_question
  | `Cmt_flag
  | `Cmt_note
  | `Cmt_approve
  | `Cmt_suggest
  | `Diff_add
  | `Diff_del
  | `Diff_add_bar
  | `Diff_del_bar
  | `Heat_1
  | `Heat_2
  | `Heat_3
  | `Color_text_body
  | `Color_text_muted
  | `Color_text_dim
  | `Color_accent_brass
  | `Color_accent_soft
  | `Color_keeper_1_glow
  | `Color_keeper_2_glow
  | `Color_keeper_3_glow
  | `Color_keeper_4_glow
  | `Color_keeper_5_glow
  | `Color_keeper_6_glow
  | `Color_keeper_7_glow
  | `Color_keeper_8_glow
  | `Color_keeper_9_glow
  | `Color_keeper_10_glow
  | `Color_keeper_11_glow
  | `Color_keeper_12_glow
  ]

(** Returns ["var(--name)"] for the given token. *)
val var_of : semantic -> string

(** Raw CSS variable name without the leading [--]. *)
val name_of : semantic -> string
