#!/usr/bin/env bash
# Unified code-smell audit wrapper.
#
# Aggregates the four point-tools introduced after the 2026-05-19
# baseline audit (memory/masc-mcp-code-smell-report-2026-05-19.html)
# into one reproducible run:
#
#   1. Godfile census         (>= 1000 LoC .ml files)
#   2. ignore() justification (scripts/lint-ignore-without-comment.sh)
#   3. Magic number repetition (scripts/lint-magic-number.sh)
#   4. Catch-all classification (scripts/audit-catchall.sh)
#      - anonymous `_` RHS-shape buckets
#      - bare binding catch-all usage buckets
#
# The wrapper produces a single Markdown-ish text report on stdout;
# redirect to a dated path to keep an evidence trail:
#
#   scripts/audit-code-smell.sh > memory/audit-code-smell-$(date +%F).md
#
# All sub-tools are informational by default. Pass `--strict` to
# require zero unjustified ignore() AND zero `other`-bucket catch-
# all arms (the two ratchet candidates). Magic-number is always
# advisory since allowlist tuning is project-specific.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

SCRIPT_DIR="$(dirname "$0")"
STRICT=0
DATE_STAMP="$(date +%F)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --strict) STRICT=1; shift ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

printf '# masc-mcp code-smell audit — %s\n\n' "$DATE_STAMP"
printf '_Generated by_ `scripts/audit-code-smell.sh` _at HEAD_ `'
git rev-parse --short HEAD 2>/dev/null || echo "unknown"
printf '`\n\n'

# 1. Godfile census
printf '## 1. Godfile census (>= 1000 LoC .ml)\n\n'
printf '| LoC | File |\n|-----|------|\n'
find lib/ -name '*.ml' -type f -print0 2>/dev/null \
  | xargs -0 wc -l 2>/dev/null \
  | awk '$2 != "total" && $1 >= 1000 && $1 < 999999 { print }' \
  | sort -rn \
  | head -20 \
  | awk '{ printf "| %d | %s |\n", $1, $2 }'

printf '\n_Total >= 1000 LoC files: '
find lib/ -name '*.ml' -type f -print0 2>/dev/null \
  | xargs -0 wc -l 2>/dev/null \
  | awk '$2 != "total" && $1 >= 1000 && $1 < 999999' \
  | wc -l \
  | tr -d ' '
printf '_\n\n'

# 2. ignore() justification
printf '## 2. ignore() lacking justification comment\n\n'
if [[ -x "$SCRIPT_DIR/lint-ignore-without-comment.sh" ]]; then
  printf '```\n'
  bash "$SCRIPT_DIR/lint-ignore-without-comment.sh" --counts 2>/dev/null | head -20 || true
  printf '```\n\n'
  unjust_n=$(bash "$SCRIPT_DIR/lint-ignore-without-comment.sh" 2>/dev/null | wc -l | tr -d ' ')
  printf '_Total unjustified ignore(): %s_\n\n' "$unjust_n"
else
  printf '_(lint-ignore-without-comment.sh not present — skipped)_\n\n'
  unjust_n=0
fi

# 3. Magic number repetition
printf '## 3. Magic-number repetition (>= 5 reps in a single file)\n\n'
if [[ -x "$SCRIPT_DIR/lint-magic-number.sh" ]]; then
  printf '```\n'
  bash "$SCRIPT_DIR/lint-magic-number.sh" 2>/dev/null | head -25 || true
  printf '```\n\n'
else
  printf '_(lint-magic-number.sh not present — skipped)_\n\n'
fi

# 4. Catch-all classification
printf '## 4. Catch-all classification\n\n'
if [[ -x "$SCRIPT_DIR/audit-catchall.sh" ]]; then
  printf '### Totals\n\n```\n'
  bash "$SCRIPT_DIR/audit-catchall.sh" 2>/dev/null || true
  printf '```\n\n### Top files\n\n```\n'
  bash "$SCRIPT_DIR/audit-catchall.sh" --by-file 2>/dev/null | head -15 || true
  printf '```\n\n### Binding use totals\n\n```\n'
  bash "$SCRIPT_DIR/audit-catchall.sh" --binding-use 2>/dev/null || true
  printf '```\n\n### Binding use top files\n\n```\n'
  bash "$SCRIPT_DIR/audit-catchall.sh" --binding-use-by-file 2>/dev/null | head -15 || true
  printf '```\n\n'
  other_n=$(bash "$SCRIPT_DIR/audit-catchall.sh" 2>/dev/null | awk '$2 == "other" { print $1 }')
  other_n="${other_n:-0}"
else
  printf '_(audit-catchall.sh not present — skipped)_\n\n'
  other_n=0
fi

# WORKAROUND inventory (informational — policy compliance check)
printf '## 5. WORKAROUND comment inventory\n\n'
wk_n=$(rg -c '(WORKAROUND|HACK:)' lib/ 2>/dev/null | awk -F: '{s+=$2} END {print s+0}')
printf '_Total WORKAROUND/HACK comment markers: %s_\n\n' "$wk_n"

if [[ "$STRICT" -eq 1 ]]; then
  fail=0
  if [[ "$unjust_n" -gt 0 ]]; then
    echo "STRICT FAIL: $unjust_n ignore() sites lack justification" >&2
    fail=1
  fi
  if [[ "$other_n" -gt 0 ]]; then
    echo "STRICT FAIL: $other_n catch-all arms in 'other' bucket" >&2
    fail=1
  fi
  [[ "$fail" -eq 1 ]] && exit 1
fi
