#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/check-version-truth.sh [--tag vX.Y.Z]
EOF
}

tag_name=""
while (($# > 0)); do
  case "$1" in
    --tag)
      shift
      (($# > 0)) || { usage >&2; exit 1; }
      tag_name="${1#v}"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
  shift
done

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

package_version="$(sed -n 's/^(version \([^)]*\)).*/\1/p' dune-project | head -n1)"
roadmap_package_version="$(sed -n 's/^> Current package version: v\([^ ]*\).*/\1/p' ROADMAP.md | head -n1)"
roadmap_changelog_entry="$(sed -n 's/^> Latest changelog entry: v\([^ ]*\).*/\1/p' ROADMAP.md | head -n1)"
roadmap_published_release="$(sed -n 's/^> Latest published GitHub release: v\([^ ]*\).*/\1/p' ROADMAP.md | head -n1)"
changelog_latest_release="$(sed -n 's/^## \[\([0-9][^]]*\)\].*/\1/p' CHANGELOG.md | head -n1)"

fail() {
  printf 'version truth check failed: %s\n' "$1" >&2
  exit 1
}

is_pr_merge_ref() {
  [[ "${GITHUB_REF:-}" =~ ^refs/pull/[0-9]+/merge$ ]]
}

# Reject CHANGELOG release section bodies that contain only "- TBD" placeholders.
# Latest section = lines after "## [version]" up to the next "## [" heading.
# Real content = non-blank, non-"### header", non-"- TBD" lines.
require_changelog_body_filled() {
  local version="$1"
  local real_lines
  real_lines="$(awk -v v="$version" '
    $0 ~ ("^## \\[" v "\\]") { found=1; next }
    found && /^## \[/ { exit }
    found {
      sub(/[[:space:]]+$/, "", $0)
      if ($0 == "" || $0 ~ /^### / || $0 == "- TBD") next
      count++
    }
    END { print count + 0 }
  ' CHANGELOG.md)"

  [[ "$real_lines" -gt 0 ]] || \
    fail "CHANGELOG.md release [$version] body is only TBD placeholders — fill before tagging"
}

changelog_has_release_heading() {
  local version="$1"
  awk -v v="$version" '
    $0 == ("## [" v "]") || index($0, "## [" v "] ") == 1 { found=1; exit }
    END { exit found ? 0 : 1 }
  ' CHANGELOG.md
}

if grep -Fq '(generate_opam_files true)' dune-project; then
  opam_version="$(sed -n 's/^version: "\([^"]*\)"/\1/p' masc_mcp.opam | head -n1)"
  if grep -Fq '# This file is generated by dune' masc_mcp.opam \
    && [[ "$opam_version" != "$package_version" ]] \
    && is_pr_merge_ref; then
    # PR merge refs can inherit a stale checked-in generated opam file from the
    # base branch. Generated opam files inherit version truth from dune-project,
    # so normalize in-memory instead of mutating the tracked file.
    opam_version="$package_version"
  fi
fi

opam_version="${opam_version:-$(sed -n 's/^version: "\([^"]*\)"/\1/p' masc_mcp.opam | head -n1)}"

[[ -n "$package_version" ]] || fail "missing package version in dune-project"
[[ -n "$opam_version" ]] || fail "missing version in masc_mcp.opam"
[[ -n "$roadmap_package_version" ]] || fail "missing current package version in ROADMAP.md"
[[ -n "$roadmap_changelog_entry" ]] || fail "missing latest changelog entry in ROADMAP.md"
[[ -n "$roadmap_published_release" ]] || fail "missing latest published GitHub release in ROADMAP.md"
grep -q "^## \[${roadmap_published_release//./\\.}\]" CHANGELOG.md || fail "CHANGELOG.md has no release heading for published release $roadmap_published_release (ROADMAP.md may contain a typo or stale value)"
[[ -n "$changelog_latest_release" ]] || fail "missing released version header in CHANGELOG.md"

require_changelog_body_filled "$changelog_latest_release"

[[ "$package_version" == "$opam_version" ]] || fail "dune-project ($package_version) != masc_mcp.opam ($opam_version)"
[[ "$package_version" == "$roadmap_package_version" ]] || fail "dune-project ($package_version) != ROADMAP current package version ($roadmap_package_version)"
[[ "$package_version" == "$changelog_latest_release" ]] || fail "dune-project ($package_version) != CHANGELOG latest release ($changelog_latest_release)"
[[ "$roadmap_changelog_entry" == "$changelog_latest_release" ]] || fail "ROADMAP latest changelog entry ($roadmap_changelog_entry) != CHANGELOG latest release ($changelog_latest_release)"
changelog_has_release_heading "$roadmap_published_release" || fail "CHANGELOG.md has no release heading for ROADMAP latest published GitHub release $roadmap_published_release"

if [[ -n "$tag_name" ]]; then
  [[ "$package_version" == "$tag_name" ]] || fail "tag v$tag_name != package version $package_version"
  changelog_has_release_heading "$tag_name" || fail "CHANGELOG.md has no release heading for $tag_name"
fi

printf 'Version truth OK: package=%s changelog_entry=%s published_release=%s\n' "$package_version" "$changelog_latest_release" "$roadmap_published_release"
