---- MODULE KeeperTraceSpec ----
\* Validates an observed trace against KeeperStateMachine safety invariants.
\* Requires TraceData.tla to be generated by bin/trace_to_tla.exe.

EXTENDS Naturals

PhaseNames ==
    {"Offline", "Running", "Failing", "Overflowed", "Compacting", "HandingOff",
     "Draining", "Paused", "Stopped", "Crashed", "Restarting", "Dead", "Zombie"}

CanTransition(from, to) ==
    CASE from = "Stopped" -> FALSE
      [] from = "Dead" -> FALSE
      [] from = "Zombie" -> FALSE
      [] from = "Offline" -> to \in {"Running", "Stopped", "Draining"}
      [] from = "Running" -> to \in {"Failing", "Overflowed", "Compacting",
                                     "HandingOff", "Draining", "Paused",
                                     "Stopped", "Crashed"}
      [] from = "Failing" -> to \in {"Running", "Overflowed", "Crashed",
                                     "Draining", "Paused", "Zombie"}
      [] from = "Overflowed" -> to \in {"Running", "Compacting", "Paused",
                                        "Draining", "Crashed"}
      [] from = "Compacting" -> to \in {"Running", "Overflowed", "Failing",
                                        "Crashed", "Draining"}
      [] from = "HandingOff" -> to \in {"Running", "Failing", "Crashed", "Draining"}
      [] from = "Draining" -> to \in {"Stopped", "Crashed"}
      [] from = "Paused" -> to \in {"Running", "Compacting", "Draining",
                                    "Stopped", "Crashed"}
      [] from = "Crashed" -> to \in {"Restarting", "Dead"}
      [] from = "Restarting" -> to \in {"Running", "Crashed", "Dead",
                                        "Draining", "Paused"}
      [] OTHER -> FALSE

CONSTANTS MaxRestarts

VARIABLES
    launch_pending,
    fiber_alive, heartbeat_healthy, turn_healthy,
    context_within_budget, context_handoff_needed,
    compaction_active, handoff_active, operator_paused,
    stop_requested, restart_budget_remaining, backoff_elapsed,
    guardrail_triggered, drain_complete,
    context_overflow, compact_retry_exhausted,
    restart_count, recorded_phase,
    trace_idx

INSTANCE TraceData

vars == <<launch_pending, fiber_alive, heartbeat_healthy, turn_healthy,
          context_within_budget, context_handoff_needed,
          compaction_active, handoff_active, operator_paused,
          stop_requested, restart_budget_remaining, backoff_elapsed,
          guardrail_triggered, drain_complete,
          context_overflow, compact_retry_exhausted,
          restart_count,
          recorded_phase, trace_idx>>

\* ── Phase Derivation (copied from KeeperStateMachine) ────

DerivePhase ==
    IF stop_requested /\ drain_complete
       /\ ~compaction_active /\ ~handoff_active THEN "Stopped"
    ELSE IF launch_pending /\ ~fiber_alive THEN "Offline"
    ELSE IF recorded_phase = "Zombie" THEN "Zombie"
    ELSE IF ~fiber_alive /\ ~restart_budget_remaining THEN "Dead"
    ELSE IF ~fiber_alive /\ restart_budget_remaining /\ backoff_elapsed THEN "Restarting"
    ELSE IF ~fiber_alive /\ restart_budget_remaining THEN "Crashed"
    ELSE IF stop_requested THEN "Draining"
    ELSE IF guardrail_triggered THEN "Failing"
    ELSE IF operator_paused \/ (context_overflow /\ compact_retry_exhausted) THEN "Paused"
    ELSE IF handoff_active THEN "HandingOff"
    ELSE IF compaction_active THEN "Compacting"
    ELSE IF context_overflow THEN "Overflowed"
    ELSE IF ~heartbeat_healthy \/ ~turn_healthy THEN "Failing"
    ELSE IF fiber_alive THEN "Running"
    ELSE "Offline"

\* ── Trace Init: load first step ──────────────────────────

TraceInit ==
    /\ trace_idx = 1
    /\ launch_pending = Trace[1].launch_pending
    /\ fiber_alive = Trace[1].fiber_alive
    /\ heartbeat_healthy = Trace[1].heartbeat_healthy
    /\ turn_healthy = Trace[1].turn_healthy
    /\ context_within_budget = Trace[1].context_within_budget
    /\ context_handoff_needed = Trace[1].context_handoff_needed
    /\ compaction_active = Trace[1].compaction_active
    /\ handoff_active = Trace[1].handoff_active
    /\ operator_paused = Trace[1].operator_paused
    /\ stop_requested = Trace[1].stop_requested
    /\ restart_budget_remaining = Trace[1].restart_budget_remaining
    /\ backoff_elapsed = Trace[1].backoff_elapsed
    /\ guardrail_triggered = Trace[1].guardrail_triggered
    /\ drain_complete = Trace[1].drain_complete
    /\ context_overflow = Trace[1].context_overflow
    /\ compact_retry_exhausted = Trace[1].compact_retry_exhausted
    /\ restart_count = Trace[1].restart_count
    /\ recorded_phase = Trace[1].recorded_phase

\* ── Trace Next: step through trace ───────────────────────

TraceNext ==
    /\ trace_idx < TraceLength
    /\ trace_idx' = trace_idx + 1
    /\ launch_pending' = Trace[trace_idx + 1].launch_pending
    /\ fiber_alive' = Trace[trace_idx + 1].fiber_alive
    /\ heartbeat_healthy' = Trace[trace_idx + 1].heartbeat_healthy
    /\ turn_healthy' = Trace[trace_idx + 1].turn_healthy
    /\ context_within_budget' = Trace[trace_idx + 1].context_within_budget
    /\ context_handoff_needed' = Trace[trace_idx + 1].context_handoff_needed
    /\ compaction_active' = Trace[trace_idx + 1].compaction_active
    /\ handoff_active' = Trace[trace_idx + 1].handoff_active
    /\ operator_paused' = Trace[trace_idx + 1].operator_paused
    /\ stop_requested' = Trace[trace_idx + 1].stop_requested
    /\ restart_budget_remaining' = Trace[trace_idx + 1].restart_budget_remaining
    /\ backoff_elapsed' = Trace[trace_idx + 1].backoff_elapsed
    /\ guardrail_triggered' = Trace[trace_idx + 1].guardrail_triggered
    /\ drain_complete' = Trace[trace_idx + 1].drain_complete
    /\ context_overflow' = Trace[trace_idx + 1].context_overflow
    /\ compact_retry_exhausted' = Trace[trace_idx + 1].compact_retry_exhausted
    /\ restart_count' = Trace[trace_idx + 1].restart_count
    /\ recorded_phase' = Trace[trace_idx + 1].recorded_phase

TerminalStutter ==
    /\ trace_idx = TraceLength
    /\ UNCHANGED vars

TraceStep ==
    \/ TraceNext
    \/ TerminalStutter

\* ── Bug Model: DerivePhase Mismatch ────────────────────────
\* Models a regression where recorded_phase diverges from DerivePhase.
\* SHOULD violate DerivePhaseAgreement.

BugDerivePhaseMismatch ==
    /\ trace_idx < TraceLength
    /\ trace_idx' = trace_idx + 1
    /\ recorded_phase' = "Running"  \* BUG: hardcoded wrong phase
    /\ UNCHANGED <<launch_pending, fiber_alive, heartbeat_healthy, turn_healthy,
                    context_within_budget, context_handoff_needed,
                    compaction_active, handoff_active, operator_paused,
                    stop_requested, restart_budget_remaining, backoff_elapsed,
                    guardrail_triggered, drain_complete,
                    context_overflow, compact_retry_exhausted,
                    restart_count>>

TraceStepBuggy ==
    \/ TraceNext
    \/ TerminalStutter
    \/ BugDerivePhaseMismatch

TraceSpecBuggy == TraceInit /\ [][TraceStepBuggy]_vars

DerivePhaseAgreementMustHold == DerivePhaseAgreement

TraceSpec == TraceInit /\ [][TraceStep]_vars

\* ── Safety Invariants ────────────────────────────────────

TypeOK ==
    /\ launch_pending \in BOOLEAN
    /\ fiber_alive \in BOOLEAN
    /\ heartbeat_healthy \in BOOLEAN
    /\ turn_healthy \in BOOLEAN
    /\ context_within_budget \in BOOLEAN
    /\ context_handoff_needed \in BOOLEAN
    /\ compaction_active \in BOOLEAN
    /\ handoff_active \in BOOLEAN
    /\ operator_paused \in BOOLEAN
    /\ stop_requested \in BOOLEAN
    /\ restart_budget_remaining \in BOOLEAN
    /\ backoff_elapsed \in BOOLEAN
    /\ guardrail_triggered \in BOOLEAN
    /\ drain_complete \in BOOLEAN
    /\ context_overflow \in BOOLEAN
    /\ compact_retry_exhausted \in BOOLEAN
    /\ restart_count \in 0..MaxRestarts+10
    /\ recorded_phase \in PhaseNames
    /\ trace_idx \in 1..TraceLength

RunningRequiresFiber == DerivePhase = "Running" => fiber_alive
OfflineRequiresLaunchPending == DerivePhase = "Offline" => (launch_pending /\ ~fiber_alive)
StoppedRequiresDrain == DerivePhase = "Stopped" => (stop_requested /\ drain_complete)
DeadRequiresNoBudget == DerivePhase = "Dead" => ~restart_budget_remaining
DerivePhaseAgreement == recorded_phase = DerivePhase

\* Monotonicity: restart_count never decreases
RestartCountMonotonic == [][restart_count' >= restart_count]_vars

\* Budget never revives
BudgetNeverRevives == [](~restart_budget_remaining => [](~restart_budget_remaining))

\* Recorded phases must either stay the same or follow the keeper transition matrix.
TransitionStepAllowed ==
    (trace_idx < TraceLength) =>
        (recorded_phase' = recorded_phase
         \/ CanTransition(recorded_phase, recorded_phase'))

TransitionMatrixAgreement == [][TransitionStepAllowed]_vars

====
